USE MovieTheatreDB;

INSERT INTO Theatre (TheatreName,Address) VALUES ('Downtown Cinemas','123 Main St');
INSERT INTO Theatre (TheatreName,Address) VALUES ('Mall Plex 12','500 Mall Rd');
INSERT INTO Theatre (TheatreName,Address) VALUES ('Riverside Movies','88 River Rd');
INSERT INTO Auditorium (TheatreID,AuditoriumName,Capacity) VALUES (1,'AUD-1-1',120);
INSERT INTO Auditorium (TheatreID,AuditoriumName,Capacity) VALUES (1,'AUD-1-2',200);
INSERT INTO Auditorium (TheatreID,AuditoriumName,Capacity) VALUES (1,'AUD-1-3',160);
INSERT INTO Auditorium (TheatreID,AuditoriumName,Capacity) VALUES (1,'AUD-1-4',120);
INSERT INTO Auditorium (TheatreID,AuditoriumName,Capacity) VALUES (1,'AUD-1-5',120);
INSERT INTO Auditorium (TheatreID,AuditoriumName,Capacity) VALUES (2,'AUD-2-1',200);
INSERT INTO Auditorium (TheatreID,AuditoriumName,Capacity) VALUES (2,'AUD-2-2',96);
INSERT INTO Auditorium (TheatreID,AuditoriumName,Capacity) VALUES (2,'AUD-2-3',200);
INSERT INTO Auditorium (TheatreID,AuditoriumName,Capacity) VALUES (2,'AUD-2-4',96);
INSERT INTO Auditorium (TheatreID,AuditoriumName,Capacity) VALUES (2,'AUD-2-5',200);
INSERT INTO SeatType (TypeName,BasePrice) VALUES ('Standard',12.0);
INSERT INTO SeatType (TypeName,BasePrice) VALUES ('Premium',15.5);
INSERT INTO SeatType (TypeName,BasePrice) VALUES ('VIP',19.0);
INSERT INTO Seat (AuditoriumID,RowLabel,SeatIndex,SeatTypeID) VALUES (1,'A',1,1);
INSERT INTO Seat (AuditoriumID,RowLabel,SeatIndex,SeatTypeID) VALUES (1,'A',2,2);
INSERT INTO Seat (AuditoriumID,RowLabel,SeatIndex,SeatTypeID) VALUES (1,'A',3,2);
INSERT INTO Seat (AuditoriumID,RowLabel,SeatIndex,SeatTypeID) VALUES (1,'A',4,1);
INSERT INTO Seat (AuditoriumID,RowLabel,SeatIndex,SeatTypeID) VALUES (1,'A',5,1);
INSERT INTO Seat (AuditoriumID,RowLabel,SeatIndex,SeatTypeID) VALUES (1,'A',6,2);
INSERT INTO Seat (AuditoriumID,RowLabel,SeatIndex,SeatTypeID) VALUES (1,'A',7,2);
INSERT INTO Seat (AuditoriumID,RowLabel,SeatIndex,SeatTypeID) VALUES (1,'A',8,1);
INSERT INTO Seat (AuditoriumID,RowLabel,SeatIndex,SeatTypeID) VALUES (1,'A',9,2);
INSERT INTO Seat (AuditoriumID,RowLabel,SeatIndex,SeatTypeID) VALUES (1,'A',10,3);
INSERT INTO Seat (AuditoriumID,RowLabel,SeatIndex,SeatTypeID) VALUES (1,'A',11,1);
INSERT INTO Seat (AuditoriumID,RowLabel,SeatIndex,SeatTypeID) VALUES (1,'A',12,1);
INSERT INTO Seat (AuditoriumID,RowLabel,SeatIndex,SeatTypeID) VALUES (1,'B',1,1);
INSERT INTO Seat (AuditoriumID,RowLabel,SeatIndex,SeatTypeID) VALUES (1,'B',2,3);
INSERT INTO Seat (AuditoriumID,RowLabel,SeatIndex,SeatTypeID) VALUES (1,'B',3,3);
INSERT INTO Seat (AuditoriumID,RowLabel,SeatIndex,SeatTypeID) VALUES (1,'B',4,2);
INSERT INTO Seat (AuditoriumID,RowLabel,SeatIndex,SeatTypeID) VALUES (1,'B',5,2);
INSERT INTO Seat (AuditoriumID,RowLabel,SeatIndex,SeatTypeID) VALUES (1,'B',6,1);
INSERT INTO Seat (AuditoriumID,RowLabel,SeatIndex,SeatTypeID) VALUES (1,'B',7,2);
INSERT INTO Seat (AuditoriumID,RowLabel,SeatIndex,SeatTypeID) VALUES (1,'B',8,2);
INSERT INTO Seat (AuditoriumID,RowLabel,SeatIndex,SeatTypeID) VALUES (1,'B',9,2);
INSERT INTO Seat (AuditoriumID,RowLabel,SeatIndex,SeatTypeID) VALUES (1,'B',10,1);
INSERT INTO Seat (AuditoriumID,RowLabel,SeatIndex,SeatTypeID) VALUES (1,'B',11,1);
INSERT INTO Seat (AuditoriumID,RowLabel,SeatIndex,SeatTypeID) VALUES (1,'B',12,2);
INSERT INTO Seat (AuditoriumID,RowLabel,SeatIndex,SeatTypeID) VALUES (1,'C',1,3);
INSERT INTO Seat (AuditoriumID,RowLabel,SeatIndex,SeatTypeID) VALUES (1,'C',2,1);
INSERT INTO Seat (AuditoriumID,RowLabel,SeatIndex,SeatTypeID) VALUES (1,'C',3,3);
INSERT INTO Seat (AuditoriumID,RowLabel,SeatIndex,SeatTypeID) VALUES (1,'C',4,2);
INSERT INTO Seat (AuditoriumID,RowLabel,SeatIndex,SeatTypeID) VALUES (1,'C',5,1);
INSERT INTO Seat (AuditoriumID,RowLabel,SeatIndex,SeatTypeID) VALUES (1,'C',6,1);
INSERT INTO Seat (AuditoriumID,RowLabel,SeatIndex,SeatTypeID) VALUES (1,'C',7,2);
INSERT INTO Seat (AuditoriumID,RowLabel,SeatIndex,SeatTypeID) VALUES (1,'C',8,1);
INSERT INTO Seat (AuditoriumID,RowLabel,SeatIndex,SeatTypeID) VALUES (1,'C',9,2);
INSERT INTO Seat (AuditoriumID,RowLabel,SeatIndex,SeatTypeID) VALUES (1,'C',10,2);
INSERT INTO Seat (AuditoriumID,RowLabel,SeatIndex,SeatTypeID) VALUES (1,'C',11,2);
INSERT INTO Seat (AuditoriumID,RowLabel,SeatIndex,SeatTypeID) VALUES (1,'C',12,2);
INSERT INTO Seat (AuditoriumID,RowLabel,SeatIndex,SeatTypeID) VALUES (1,'D',1,2);
INSERT INTO Seat (AuditoriumID,RowLabel,SeatIndex,SeatTypeID) VALUES (1,'D',2,1);
INSERT INTO Seat (AuditoriumID,RowLabel,SeatIndex,SeatTypeID) VALUES (1,'D',3,1);
INSERT INTO Seat (AuditoriumID,RowLabel,SeatIndex,SeatTypeID) VALUES (1,'D',4,2);
INSERT INTO Seat (AuditoriumID,RowLabel,SeatIndex,SeatTypeID) VALUES (1,'D',5,1);
INSERT INTO Seat (AuditoriumID,RowLabel,SeatIndex,SeatTypeID) VALUES (1,'D',6,2);
INSERT INTO Seat (AuditoriumID,RowLabel,SeatIndex,SeatTypeID) VALUES (1,'D',7,2);
INSERT INTO Seat (AuditoriumID,RowLabel,SeatIndex,SeatTypeID) VALUES (1,'D',8,3);
INSERT INTO Seat (AuditoriumID,RowLabel,SeatIndex,SeatTypeID) VALUES (1,'D',9,3);
INSERT INTO Seat (AuditoriumID,RowLabel,SeatIndex,SeatTypeID) VALUES (1,'D',10,3);
INSERT INTO Seat (AuditoriumID,RowLabel,SeatIndex,SeatTypeID) VALUES (1,'D',11,2);
INSERT INTO Seat (AuditoriumID,RowLabel,SeatIndex,SeatTypeID) VALUES (1,'D',12,3);
INSERT INTO Seat (AuditoriumID,RowLabel,SeatIndex,SeatTypeID) VALUES (2,'A',1,3);
INSERT INTO Seat (AuditoriumID,RowLabel,SeatIndex,SeatTypeID) VALUES (2,'A',2,2);
INSERT INTO Seat (AuditoriumID,RowLabel,SeatIndex,SeatTypeID) VALUES (2,'A',3,2);
INSERT INTO Seat (AuditoriumID,RowLabel,SeatIndex,SeatTypeID) VALUES (2,'A',4,1);
INSERT INTO Seat (AuditoriumID,RowLabel,SeatIndex,SeatTypeID) VALUES (2,'A',5,1);
INSERT INTO Seat (AuditoriumID,RowLabel,SeatIndex,SeatTypeID) VALUES (2,'A',6,2);
INSERT INTO Seat (AuditoriumID,RowLabel,SeatIndex,SeatTypeID) VALUES (2,'A',7,1);
INSERT INTO Seat (AuditoriumID,RowLabel,SeatIndex,SeatTypeID) VALUES (2,'A',8,3);
INSERT INTO Seat (AuditoriumID,RowLabel,SeatIndex,SeatTypeID) VALUES (2,'A',9,3);
INSERT INTO Seat (AuditoriumID,RowLabel,SeatIndex,SeatTypeID) VALUES (2,'A',10,2);
INSERT INTO Seat (AuditoriumID,RowLabel,SeatIndex,SeatTypeID) VALUES (2,'A',11,1);
INSERT INTO Seat (AuditoriumID,RowLabel,SeatIndex,SeatTypeID) VALUES (2,'A',12,2);
INSERT INTO Seat (AuditoriumID,RowLabel,SeatIndex,SeatTypeID) VALUES (2,'B',1,2);
INSERT INTO Seat (AuditoriumID,RowLabel,SeatIndex,SeatTypeID) VALUES (2,'B',2,3);
INSERT INTO Seat (AuditoriumID,RowLabel,SeatIndex,SeatTypeID) VALUES (2,'B',3,3);
INSERT INTO Seat (AuditoriumID,RowLabel,SeatIndex,SeatTypeID) VALUES (2,'B',4,1);
INSERT INTO Seat (AuditoriumID,RowLabel,SeatIndex,SeatTypeID) VALUES (2,'B',5,2);
INSERT INTO Seat (AuditoriumID,RowLabel,SeatIndex,SeatTypeID) VALUES (2,'B',6,2);
INSERT INTO Seat (AuditoriumID,RowLabel,SeatIndex,SeatTypeID) VALUES (2,'B',7,2);
INSERT INTO Seat (AuditoriumID,RowLabel,SeatIndex,SeatTypeID) VALUES (2,'B',8,1);
INSERT INTO Seat (AuditoriumID,RowLabel,SeatIndex,SeatTypeID) VALUES (2,'B',9,2);
INSERT INTO Seat (AuditoriumID,RowLabel,SeatIndex,SeatTypeID) VALUES (2,'B',10,3);
INSERT INTO Seat (AuditoriumID,RowLabel,SeatIndex,SeatTypeID) VALUES (2,'B',11,3);
INSERT INTO Seat (AuditoriumID,RowLabel,SeatIndex,SeatTypeID) VALUES (2,'B',12,2);
INSERT INTO Seat (AuditoriumID,RowLabel,SeatIndex,SeatTypeID) VALUES (2,'C',1,1);
INSERT INTO Seat (AuditoriumID,RowLabel,SeatIndex,SeatTypeID) VALUES (2,'C',2,3);
INSERT INTO Seat (AuditoriumID,RowLabel,SeatIndex,SeatTypeID) VALUES (2,'C',3,3);
INSERT INTO Seat (AuditoriumID,RowLabel,SeatIndex,SeatTypeID) VALUES (2,'C',4,2);
INSERT INTO Seat (AuditoriumID,RowLabel,SeatIndex,SeatTypeID) VALUES (2,'C',5,3);
INSERT INTO Seat (AuditoriumID,RowLabel,SeatIndex,SeatTypeID) VALUES (2,'C',6,3);
INSERT INTO Seat (AuditoriumID,RowLabel,SeatIndex,SeatTypeID) VALUES (2,'C',7,2);
INSERT INTO Seat (AuditoriumID,RowLabel,SeatIndex,SeatTypeID) VALUES (2,'C',8,1);
INSERT INTO Seat (AuditoriumID,RowLabel,SeatIndex,SeatTypeID) VALUES (2,'C',9,2);
INSERT INTO Seat (AuditoriumID,RowLabel,SeatIndex,SeatTypeID) VALUES (2,'C',10,2);
INSERT INTO Seat (AuditoriumID,RowLabel,SeatIndex,SeatTypeID) VALUES (2,'C',11,2);
INSERT INTO Seat (AuditoriumID,RowLabel,SeatIndex,SeatTypeID) VALUES (2,'C',12,2);
INSERT INTO Seat (AuditoriumID,RowLabel,SeatIndex,SeatTypeID) VALUES (2,'D',1,1);
INSERT INTO Seat (AuditoriumID,RowLabel,SeatIndex,SeatTypeID) VALUES (2,'D',2,3);
INSERT INTO Seat (AuditoriumID,RowLabel,SeatIndex,SeatTypeID) VALUES (2,'D',3,2);
INSERT INTO Seat (AuditoriumID,RowLabel,SeatIndex,SeatTypeID) VALUES (2,'D',4,3);
INSERT INTO Seat (AuditoriumID,RowLabel,SeatIndex,SeatTypeID) VALUES (2,'D',5,1);
INSERT INTO Seat (AuditoriumID,RowLabel,SeatIndex,SeatTypeID) VALUES (2,'D',6,3);
INSERT INTO Seat (AuditoriumID,RowLabel,SeatIndex,SeatTypeID) VALUES (2,'D',7,3);
INSERT INTO Seat (AuditoriumID,RowLabel,SeatIndex,SeatTypeID) VALUES (2,'D',8,2);
INSERT INTO Seat (AuditoriumID,RowLabel,SeatIndex,SeatTypeID) VALUES (2,'D',9,2);
INSERT INTO Seat (AuditoriumID,RowLabel,SeatIndex,SeatTypeID) VALUES (2,'D',10,2);
INSERT INTO Seat (AuditoriumID,RowLabel,SeatIndex,SeatTypeID) VALUES (2,'D',11,3);
INSERT INTO Seat (AuditoriumID,RowLabel,SeatIndex,SeatTypeID) VALUES (2,'D',12,2);
INSERT INTO Seat (AuditoriumID,RowLabel,SeatIndex,SeatTypeID) VALUES (3,'A',1,2);
INSERT INTO Seat (AuditoriumID,RowLabel,SeatIndex,SeatTypeID) VALUES (3,'A',2,1);
INSERT INTO Seat (AuditoriumID,RowLabel,SeatIndex,SeatTypeID) VALUES (3,'A',3,3);
INSERT INTO Seat (AuditoriumID,RowLabel,SeatIndex,SeatTypeID) VALUES (3,'A',4,2);
INSERT INTO Seat (AuditoriumID,RowLabel,SeatIndex,SeatTypeID) VALUES (3,'A',5,2);
INSERT INTO Seat (AuditoriumID,RowLabel,SeatIndex,SeatTypeID) VALUES (3,'A',6,3);
INSERT INTO Seat (AuditoriumID,RowLabel,SeatIndex,SeatTypeID) VALUES (3,'A',7,1);
INSERT INTO Seat (AuditoriumID,RowLabel,SeatIndex,SeatTypeID) VALUES (3,'A',8,1);
INSERT INTO Seat (AuditoriumID,RowLabel,SeatIndex,SeatTypeID) VALUES (3,'A',9,1);
INSERT INTO Seat (AuditoriumID,RowLabel,SeatIndex,SeatTypeID) VALUES (3,'A',10,3);
INSERT INTO Seat (AuditoriumID,RowLabel,SeatIndex,SeatTypeID) VALUES (3,'A',11,1);
INSERT INTO Seat (AuditoriumID,RowLabel,SeatIndex,SeatTypeID) VALUES (3,'A',12,2);
INSERT INTO Seat (AuditoriumID,RowLabel,SeatIndex,SeatTypeID) VALUES (3,'B',1,2);
INSERT INTO Seat (AuditoriumID,RowLabel,SeatIndex,SeatTypeID) VALUES (3,'B',2,2);
INSERT INTO Seat (AuditoriumID,RowLabel,SeatIndex,SeatTypeID) VALUES (3,'B',3,1);
INSERT INTO Seat (AuditoriumID,RowLabel,SeatIndex,SeatTypeID) VALUES (3,'B',4,3);
INSERT INTO Seat (AuditoriumID,RowLabel,SeatIndex,SeatTypeID) VALUES (3,'B',5,3);
INSERT INTO Seat (AuditoriumID,RowLabel,SeatIndex,SeatTypeID) VALUES (3,'B',6,3);
INSERT INTO Seat (AuditoriumID,RowLabel,SeatIndex,SeatTypeID) VALUES (3,'B',7,2);
INSERT INTO Seat (AuditoriumID,RowLabel,SeatIndex,SeatTypeID) VALUES (3,'B',8,3);
INSERT INTO Seat (AuditoriumID,RowLabel,SeatIndex,SeatTypeID) VALUES (3,'B',9,2);
INSERT INTO Seat (AuditoriumID,RowLabel,SeatIndex,SeatTypeID) VALUES (3,'B',10,2);
INSERT INTO Seat (AuditoriumID,RowLabel,SeatIndex,SeatTypeID) VALUES (3,'B',11,1);
INSERT INTO Seat (AuditoriumID,RowLabel,SeatIndex,SeatTypeID) VALUES (3,'B',12,3);
INSERT INTO Seat (AuditoriumID,RowLabel,SeatIndex,SeatTypeID) VALUES (3,'C',1,2);
INSERT INTO Seat (AuditoriumID,RowLabel,SeatIndex,SeatTypeID) VALUES (3,'C',2,1);
INSERT INTO Seat (AuditoriumID,RowLabel,SeatIndex,SeatTypeID) VALUES (3,'C',3,1);
INSERT INTO Seat (AuditoriumID,RowLabel,SeatIndex,SeatTypeID) VALUES (3,'C',4,2);
INSERT INTO Seat (AuditoriumID,RowLabel,SeatIndex,SeatTypeID) VALUES (3,'C',5,3);
INSERT INTO Seat (AuditoriumID,RowLabel,SeatIndex,SeatTypeID) VALUES (3,'C',6,1);
INSERT INTO Seat (AuditoriumID,RowLabel,SeatIndex,SeatTypeID) VALUES (3,'C',7,1);
INSERT INTO Seat (AuditoriumID,RowLabel,SeatIndex,SeatTypeID) VALUES (3,'C',8,2);
INSERT INTO Seat (AuditoriumID,RowLabel,SeatIndex,SeatTypeID) VALUES (3,'C',9,2);
INSERT INTO Seat (AuditoriumID,RowLabel,SeatIndex,SeatTypeID) VALUES (3,'C',10,2);
INSERT INTO Seat (AuditoriumID,RowLabel,SeatIndex,SeatTypeID) VALUES (3,'C',11,3);
INSERT INTO Seat (AuditoriumID,RowLabel,SeatIndex,SeatTypeID) VALUES (3,'C',12,1);
INSERT INTO Seat (AuditoriumID,RowLabel,SeatIndex,SeatTypeID) VALUES (3,'D',1,3);
INSERT INTO Seat (AuditoriumID,RowLabel,SeatIndex,SeatTypeID) VALUES (3,'D',2,2);
INSERT INTO Seat (AuditoriumID,RowLabel,SeatIndex,SeatTypeID) VALUES (3,'D',3,2);
INSERT INTO Seat (AuditoriumID,RowLabel,SeatIndex,SeatTypeID) VALUES (3,'D',4,3);
INSERT INTO Seat (AuditoriumID,RowLabel,SeatIndex,SeatTypeID) VALUES (3,'D',5,2);
INSERT INTO Seat (AuditoriumID,RowLabel,SeatIndex,SeatTypeID) VALUES (3,'D',6,3);
INSERT INTO Seat (AuditoriumID,RowLabel,SeatIndex,SeatTypeID) VALUES (3,'D',7,3);
INSERT INTO Seat (AuditoriumID,RowLabel,SeatIndex,SeatTypeID) VALUES (3,'D',8,1);
INSERT INTO Seat (AuditoriumID,RowLabel,SeatIndex,SeatTypeID) VALUES (3,'D',9,3);
INSERT INTO Seat (AuditoriumID,RowLabel,SeatIndex,SeatTypeID) VALUES (3,'D',10,1);
INSERT INTO Seat (AuditoriumID,RowLabel,SeatIndex,SeatTypeID) VALUES (3,'D',11,1);
INSERT INTO Seat (AuditoriumID,RowLabel,SeatIndex,SeatTypeID) VALUES (3,'D',12,3);
INSERT INTO Movie (Title,Language,Runtime,MPAA,ReleaseDate) VALUES ('Movie 1','English',91,'PG','2024-01-01');
INSERT INTO Movie (Title,Language,Runtime,MPAA,ReleaseDate) VALUES ('Movie 2','English',92,'PG','2024-01-02');
INSERT INTO Movie (Title,Language,Runtime,MPAA,ReleaseDate) VALUES ('Movie 3','English',93,'PG','2024-01-03');
INSERT INTO Movie (Title,Language,Runtime,MPAA,ReleaseDate) VALUES ('Movie 4','English',94,'PG','2024-01-04');
INSERT INTO Movie (Title,Language,Runtime,MPAA,ReleaseDate) VALUES ('Movie 5','English',95,'PG','2024-01-05');
INSERT INTO Movie (Title,Language,Runtime,MPAA,ReleaseDate) VALUES ('Movie 6','English',96,'PG','2024-01-06');
INSERT INTO Movie (Title,Language,Runtime,MPAA,ReleaseDate) VALUES ('Movie 7','English',97,'PG','2024-01-07');
INSERT INTO Movie (Title,Language,Runtime,MPAA,ReleaseDate) VALUES ('Movie 8','English',98,'PG','2024-01-08');
INSERT INTO Movie (Title,Language,Runtime,MPAA,ReleaseDate) VALUES ('Movie 9','English',99,'PG','2024-01-09');
INSERT INTO Movie (Title,Language,Runtime,MPAA,ReleaseDate) VALUES ('Movie 10','English',100,'PG','2024-01-10');
INSERT INTO Movie (Title,Language,Runtime,MPAA,ReleaseDate) VALUES ('Movie 11','English',101,'PG','2024-01-11');
INSERT INTO Movie (Title,Language,Runtime,MPAA,ReleaseDate) VALUES ('Movie 12','English',102,'PG','2024-01-12');
INSERT INTO Showtime (AuditoriumID,MovieID,StartTime,EndTime,Format) VALUES (7,12,'2024-02-01 12:00:00','2024-02-01 14:00:00','2D');
INSERT INTO Showtime (AuditoriumID,MovieID,StartTime,EndTime,Format) VALUES (9,6,'2024-02-01 14:00:00','2024-02-01 16:00:00','2D');
INSERT INTO Showtime (AuditoriumID,MovieID,StartTime,EndTime,Format) VALUES (10,8,'2024-02-01 16:00:00','2024-02-01 18:00:00','2D');
INSERT INTO Showtime (AuditoriumID,MovieID,StartTime,EndTime,Format) VALUES (4,5,'2024-02-01 18:00:00','2024-02-01 20:00:00','2D');
INSERT INTO Showtime (AuditoriumID,MovieID,StartTime,EndTime,Format) VALUES (2,8,'2024-02-01 20:00:00','2024-02-01 22:00:00','2D');
INSERT INTO Showtime (AuditoriumID,MovieID,StartTime,EndTime,Format) VALUES (2,5,'2024-02-01 22:00:00','2024-02-02 00:00:00','2D');
INSERT INTO Showtime (AuditoriumID,MovieID,StartTime,EndTime,Format) VALUES (7,2,'2024-02-02 00:00:00','2024-02-02 02:00:00','2D');
INSERT INTO Showtime (AuditoriumID,MovieID,StartTime,EndTime,Format) VALUES (5,8,'2024-02-02 02:00:00','2024-02-02 04:00:00','2D');
INSERT INTO Showtime (AuditoriumID,MovieID,StartTime,EndTime,Format) VALUES (4,2,'2024-02-02 04:00:00','2024-02-02 06:00:00','2D');
INSERT INTO Showtime (AuditoriumID,MovieID,StartTime,EndTime,Format) VALUES (9,6,'2024-02-02 06:00:00','2024-02-02 08:00:00','2D');
INSERT INTO Showtime (AuditoriumID,MovieID,StartTime,EndTime,Format) VALUES (9,7,'2024-02-02 08:00:00','2024-02-02 10:00:00','2D');
INSERT INTO Showtime (AuditoriumID,MovieID,StartTime,EndTime,Format) VALUES (5,3,'2024-02-02 10:00:00','2024-02-02 12:00:00','2D');
INSERT INTO Showtime (AuditoriumID,MovieID,StartTime,EndTime,Format) VALUES (4,6,'2024-02-02 12:00:00','2024-02-02 14:00:00','2D');
INSERT INTO Showtime (AuditoriumID,MovieID,StartTime,EndTime,Format) VALUES (2,2,'2024-02-02 14:00:00','2024-02-02 16:00:00','2D');
INSERT INTO Showtime (AuditoriumID,MovieID,StartTime,EndTime,Format) VALUES (10,2,'2024-02-02 16:00:00','2024-02-02 18:00:00','2D');
INSERT INTO Showtime (AuditoriumID,MovieID,StartTime,EndTime,Format) VALUES (10,9,'2024-02-02 18:00:00','2024-02-02 20:00:00','2D');
INSERT INTO Showtime (AuditoriumID,MovieID,StartTime,EndTime,Format) VALUES (10,2,'2024-02-02 20:00:00','2024-02-02 22:00:00','2D');
INSERT INTO Showtime (AuditoriumID,MovieID,StartTime,EndTime,Format) VALUES (6,1,'2024-02-02 22:00:00','2024-02-03 00:00:00','2D');
INSERT INTO Showtime (AuditoriumID,MovieID,StartTime,EndTime,Format) VALUES (9,5,'2024-02-03 00:00:00','2024-02-03 02:00:00','2D');
INSERT INTO Showtime (AuditoriumID,MovieID,StartTime,EndTime,Format) VALUES (9,1,'2024-02-03 02:00:00','2024-02-03 04:00:00','2D');
INSERT INTO Showtime (AuditoriumID,MovieID,StartTime,EndTime,Format) VALUES (7,1,'2024-02-03 04:00:00','2024-02-03 06:00:00','2D');
INSERT INTO Showtime (AuditoriumID,MovieID,StartTime,EndTime,Format) VALUES (3,12,'2024-02-03 06:00:00','2024-02-03 08:00:00','2D');
INSERT INTO Showtime (AuditoriumID,MovieID,StartTime,EndTime,Format) VALUES (3,7,'2024-02-03 08:00:00','2024-02-03 10:00:00','2D');
INSERT INTO Showtime (AuditoriumID,MovieID,StartTime,EndTime,Format) VALUES (6,7,'2024-02-03 10:00:00','2024-02-03 12:00:00','2D');
INSERT INTO Showtime (AuditoriumID,MovieID,StartTime,EndTime,Format) VALUES (9,4,'2024-02-03 12:00:00','2024-02-03 14:00:00','2D');
INSERT INTO Showtime (AuditoriumID,MovieID,StartTime,EndTime,Format) VALUES (8,7,'2024-02-03 14:00:00','2024-02-03 16:00:00','2D');
INSERT INTO Showtime (AuditoriumID,MovieID,StartTime,EndTime,Format) VALUES (6,8,'2024-02-03 16:00:00','2024-02-03 18:00:00','2D');
INSERT INTO Showtime (AuditoriumID,MovieID,StartTime,EndTime,Format) VALUES (2,2,'2024-02-03 18:00:00','2024-02-03 20:00:00','2D');
INSERT INTO Showtime (AuditoriumID,MovieID,StartTime,EndTime,Format) VALUES (1,12,'2024-02-03 20:00:00','2024-02-03 22:00:00','2D');
INSERT INTO Showtime (AuditoriumID,MovieID,StartTime,EndTime,Format) VALUES (7,2,'2024-02-03 22:00:00','2024-02-04 00:00:00','2D');
INSERT INTO Showtime (AuditoriumID,MovieID,StartTime,EndTime,Format) VALUES (9,4,'2024-02-04 00:00:00','2024-02-04 02:00:00','2D');
INSERT INTO Showtime (AuditoriumID,MovieID,StartTime,EndTime,Format) VALUES (5,6,'2024-02-04 02:00:00','2024-02-04 04:00:00','2D');
INSERT INTO Showtime (AuditoriumID,MovieID,StartTime,EndTime,Format) VALUES (3,1,'2024-02-04 04:00:00','2024-02-04 06:00:00','2D');
INSERT INTO Showtime (AuditoriumID,MovieID,StartTime,EndTime,Format) VALUES (7,3,'2024-02-04 06:00:00','2024-02-04 08:00:00','2D');
INSERT INTO Showtime (AuditoriumID,MovieID,StartTime,EndTime,Format) VALUES (5,3,'2024-02-04 08:00:00','2024-02-04 10:00:00','2D');
INSERT INTO Showtime (AuditoriumID,MovieID,StartTime,EndTime,Format) VALUES (4,10,'2024-02-04 10:00:00','2024-02-04 12:00:00','2D');
INSERT INTO Showtime (AuditoriumID,MovieID,StartTime,EndTime,Format) VALUES (8,8,'2024-02-04 12:00:00','2024-02-04 14:00:00','2D');
INSERT INTO Showtime (AuditoriumID,MovieID,StartTime,EndTime,Format) VALUES (7,12,'2024-02-04 14:00:00','2024-02-04 16:00:00','2D');
INSERT INTO Showtime (AuditoriumID,MovieID,StartTime,EndTime,Format) VALUES (1,5,'2024-02-04 16:00:00','2024-02-04 18:00:00','2D');
INSERT INTO Showtime (AuditoriumID,MovieID,StartTime,EndTime,Format) VALUES (3,2,'2024-02-04 18:00:00','2024-02-04 20:00:00','2D');
INSERT INTO Showtime (AuditoriumID,MovieID,StartTime,EndTime,Format) VALUES (7,3,'2024-02-04 20:00:00','2024-02-04 22:00:00','2D');
INSERT INTO Showtime (AuditoriumID,MovieID,StartTime,EndTime,Format) VALUES (10,8,'2024-02-04 22:00:00','2024-02-05 00:00:00','2D');
INSERT INTO Showtime (AuditoriumID,MovieID,StartTime,EndTime,Format) VALUES (5,12,'2024-02-05 00:00:00','2024-02-05 02:00:00','2D');
INSERT INTO Showtime (AuditoriumID,MovieID,StartTime,EndTime,Format) VALUES (10,1,'2024-02-05 02:00:00','2024-02-05 04:00:00','2D');
INSERT INTO Showtime (AuditoriumID,MovieID,StartTime,EndTime,Format) VALUES (8,6,'2024-02-05 04:00:00','2024-02-05 06:00:00','2D');
INSERT INTO Showtime (AuditoriumID,MovieID,StartTime,EndTime,Format) VALUES (6,2,'2024-02-05 06:00:00','2024-02-05 08:00:00','2D');
INSERT INTO Showtime (AuditoriumID,MovieID,StartTime,EndTime,Format) VALUES (7,10,'2024-02-05 08:00:00','2024-02-05 10:00:00','2D');
INSERT INTO Showtime (AuditoriumID,MovieID,StartTime,EndTime,Format) VALUES (1,1,'2024-02-05 10:00:00','2024-02-05 12:00:00','2D');
INSERT INTO Showtime (AuditoriumID,MovieID,StartTime,EndTime,Format) VALUES (4,5,'2024-02-05 12:00:00','2024-02-05 14:00:00','2D');
INSERT INTO Showtime (AuditoriumID,MovieID,StartTime,EndTime,Format) VALUES (8,12,'2024-02-05 14:00:00','2024-02-05 16:00:00','2D');
INSERT INTO Showtime (AuditoriumID,MovieID,StartTime,EndTime,Format) VALUES (1,12,'2024-02-05 16:00:00','2024-02-05 18:00:00','2D');
INSERT INTO Showtime (AuditoriumID,MovieID,StartTime,EndTime,Format) VALUES (8,1,'2024-02-05 18:00:00','2024-02-05 20:00:00','2D');
INSERT INTO Showtime (AuditoriumID,MovieID,StartTime,EndTime,Format) VALUES (5,3,'2024-02-05 20:00:00','2024-02-05 22:00:00','2D');
INSERT INTO Showtime (AuditoriumID,MovieID,StartTime,EndTime,Format) VALUES (10,11,'2024-02-05 22:00:00','2024-02-06 00:00:00','2D');
INSERT INTO Showtime (AuditoriumID,MovieID,StartTime,EndTime,Format) VALUES (6,4,'2024-02-06 00:00:00','2024-02-06 02:00:00','2D');
INSERT INTO Showtime (AuditoriumID,MovieID,StartTime,EndTime,Format) VALUES (5,9,'2024-02-06 02:00:00','2024-02-06 04:00:00','2D');
INSERT INTO Showtime (AuditoriumID,MovieID,StartTime,EndTime,Format) VALUES (9,12,'2024-02-06 04:00:00','2024-02-06 06:00:00','2D');
INSERT INTO Showtime (AuditoriumID,MovieID,StartTime,EndTime,Format) VALUES (4,11,'2024-02-06 06:00:00','2024-02-06 08:00:00','2D');
INSERT INTO Showtime (AuditoriumID,MovieID,StartTime,EndTime,Format) VALUES (3,6,'2024-02-06 08:00:00','2024-02-06 10:00:00','2D');
INSERT INTO Showtime (AuditoriumID,MovieID,StartTime,EndTime,Format) VALUES (5,5,'2024-02-06 10:00:00','2024-02-06 12:00:00','2D');
INSERT INTO Showtime (AuditoriumID,MovieID,StartTime,EndTime,Format) VALUES (7,3,'2024-02-06 12:00:00','2024-02-06 14:00:00','2D');
INSERT INTO Showtime (AuditoriumID,MovieID,StartTime,EndTime,Format) VALUES (6,3,'2024-02-06 14:00:00','2024-02-06 16:00:00','2D');
INSERT INTO Showtime (AuditoriumID,MovieID,StartTime,EndTime,Format) VALUES (2,3,'2024-02-06 16:00:00','2024-02-06 18:00:00','2D');
INSERT INTO Showtime (AuditoriumID,MovieID,StartTime,EndTime,Format) VALUES (7,11,'2024-02-06 18:00:00','2024-02-06 20:00:00','2D');
INSERT INTO Showtime (AuditoriumID,MovieID,StartTime,EndTime,Format) VALUES (3,4,'2024-02-06 20:00:00','2024-02-06 22:00:00','2D');
INSERT INTO Showtime (AuditoriumID,MovieID,StartTime,EndTime,Format) VALUES (8,2,'2024-02-06 22:00:00','2024-02-07 00:00:00','2D');
INSERT INTO Showtime (AuditoriumID,MovieID,StartTime,EndTime,Format) VALUES (5,3,'2024-02-07 00:00:00','2024-02-07 02:00:00','2D');
INSERT INTO Showtime (AuditoriumID,MovieID,StartTime,EndTime,Format) VALUES (4,1,'2024-02-07 02:00:00','2024-02-07 04:00:00','2D');
INSERT INTO Showtime (AuditoriumID,MovieID,StartTime,EndTime,Format) VALUES (10,8,'2024-02-07 04:00:00','2024-02-07 06:00:00','2D');
INSERT INTO Showtime (AuditoriumID,MovieID,StartTime,EndTime,Format) VALUES (4,10,'2024-02-07 06:00:00','2024-02-07 08:00:00','2D');
INSERT INTO Showtime (AuditoriumID,MovieID,StartTime,EndTime,Format) VALUES (5,9,'2024-02-07 08:00:00','2024-02-07 10:00:00','2D');
INSERT INTO Showtime (AuditoriumID,MovieID,StartTime,EndTime,Format) VALUES (5,4,'2024-02-07 10:00:00','2024-02-07 12:00:00','2D');
INSERT INTO Showtime (AuditoriumID,MovieID,StartTime,EndTime,Format) VALUES (5,9,'2024-02-07 12:00:00','2024-02-07 14:00:00','2D');
INSERT INTO Showtime (AuditoriumID,MovieID,StartTime,EndTime,Format) VALUES (4,8,'2024-02-07 14:00:00','2024-02-07 16:00:00','2D');
INSERT INTO Showtime (AuditoriumID,MovieID,StartTime,EndTime,Format) VALUES (2,7,'2024-02-07 16:00:00','2024-02-07 18:00:00','2D');
INSERT INTO Showtime (AuditoriumID,MovieID,StartTime,EndTime,Format) VALUES (10,1,'2024-02-07 18:00:00','2024-02-07 20:00:00','2D');
INSERT INTO Showtime (AuditoriumID,MovieID,StartTime,EndTime,Format) VALUES (3,12,'2024-02-07 20:00:00','2024-02-07 22:00:00','2D');
INSERT INTO Showtime (AuditoriumID,MovieID,StartTime,EndTime,Format) VALUES (7,1,'2024-02-07 22:00:00','2024-02-08 00:00:00','2D');
INSERT INTO Showtime (AuditoriumID,MovieID,StartTime,EndTime,Format) VALUES (1,6,'2024-02-08 00:00:00','2024-02-08 02:00:00','2D');
INSERT INTO Showtime (AuditoriumID,MovieID,StartTime,EndTime,Format) VALUES (9,4,'2024-02-08 02:00:00','2024-02-08 04:00:00','2D');
INSERT INTO Customer (CustomerName,Email) VALUES ('Customer 1','cust1@mail.com');
INSERT INTO Customer (CustomerName,Email) VALUES ('Customer 2','cust2@mail.com');
INSERT INTO Customer (CustomerName,Email) VALUES ('Customer 3','cust3@mail.com');
INSERT INTO Customer (CustomerName,Email) VALUES ('Customer 4','cust4@mail.com');
INSERT INTO Customer (CustomerName,Email) VALUES ('Customer 5','cust5@mail.com');
INSERT INTO Customer (CustomerName,Email) VALUES ('Customer 6','cust6@mail.com');
INSERT INTO Customer (CustomerName,Email) VALUES ('Customer 7','cust7@mail.com');
INSERT INTO Customer (CustomerName,Email) VALUES ('Customer 8','cust8@mail.com');
INSERT INTO Customer (CustomerName,Email) VALUES ('Customer 9','cust9@mail.com');
INSERT INTO Customer (CustomerName,Email) VALUES ('Customer 10','cust10@mail.com');
INSERT INTO Customer (CustomerName,Email) VALUES ('Customer 11','cust11@mail.com');
INSERT INTO Customer (CustomerName,Email) VALUES ('Customer 12','cust12@mail.com');
INSERT INTO Customer (CustomerName,Email) VALUES ('Customer 13','cust13@mail.com');
INSERT INTO Customer (CustomerName,Email) VALUES ('Customer 14','cust14@mail.com');
INSERT INTO Customer (CustomerName,Email) VALUES ('Customer 15','cust15@mail.com');
INSERT INTO Customer (CustomerName,Email) VALUES ('Customer 16','cust16@mail.com');
INSERT INTO Customer (CustomerName,Email) VALUES ('Customer 17','cust17@mail.com');
INSERT INTO Customer (CustomerName,Email) VALUES ('Customer 18','cust18@mail.com');
INSERT INTO Customer (CustomerName,Email) VALUES ('Customer 19','cust19@mail.com');
INSERT INTO Customer (CustomerName,Email) VALUES ('Customer 20','cust20@mail.com');
INSERT INTO Customer (CustomerName,Email) VALUES ('Customer 21','cust21@mail.com');
INSERT INTO Customer (CustomerName,Email) VALUES ('Customer 22','cust22@mail.com');
INSERT INTO Customer (CustomerName,Email) VALUES ('Customer 23','cust23@mail.com');
INSERT INTO Customer (CustomerName,Email) VALUES ('Customer 24','cust24@mail.com');
INSERT INTO Customer (CustomerName,Email) VALUES ('Customer 25','cust25@mail.com');
INSERT INTO Customer (CustomerName,Email) VALUES ('Customer 26','cust26@mail.com');
INSERT INTO Customer (CustomerName,Email) VALUES ('Customer 27','cust27@mail.com');
INSERT INTO Customer (CustomerName,Email) VALUES ('Customer 28','cust28@mail.com');
INSERT INTO Customer (CustomerName,Email) VALUES ('Customer 29','cust29@mail.com');
INSERT INTO Customer (CustomerName,Email) VALUES ('Customer 30','cust30@mail.com');
INSERT INTO Customer (CustomerName,Email) VALUES ('Customer 31','cust31@mail.com');
INSERT INTO Customer (CustomerName,Email) VALUES ('Customer 32','cust32@mail.com');
INSERT INTO Customer (CustomerName,Email) VALUES ('Customer 33','cust33@mail.com');
INSERT INTO Customer (CustomerName,Email) VALUES ('Customer 34','cust34@mail.com');
INSERT INTO Customer (CustomerName,Email) VALUES ('Customer 35','cust35@mail.com');
INSERT INTO Customer (CustomerName,Email) VALUES ('Customer 36','cust36@mail.com');
INSERT INTO Customer (CustomerName,Email) VALUES ('Customer 37','cust37@mail.com');
INSERT INTO Customer (CustomerName,Email) VALUES ('Customer 38','cust38@mail.com');
INSERT INTO Customer (CustomerName,Email) VALUES ('Customer 39','cust39@mail.com');
INSERT INTO Customer (CustomerName,Email) VALUES ('Customer 40','cust40@mail.com');
INSERT INTO Customer (CustomerName,Email) VALUES ('Customer 41','cust41@mail.com');
INSERT INTO Customer (CustomerName,Email) VALUES ('Customer 42','cust42@mail.com');
INSERT INTO Customer (CustomerName,Email) VALUES ('Customer 43','cust43@mail.com');
INSERT INTO Customer (CustomerName,Email) VALUES ('Customer 44','cust44@mail.com');
INSERT INTO Customer (CustomerName,Email) VALUES ('Customer 45','cust45@mail.com');
INSERT INTO Customer (CustomerName,Email) VALUES ('Customer 46','cust46@mail.com');
INSERT INTO Customer (CustomerName,Email) VALUES ('Customer 47','cust47@mail.com');
INSERT INTO Customer (CustomerName,Email) VALUES ('Customer 48','cust48@mail.com');
INSERT INTO Customer (CustomerName,Email) VALUES ('Customer 49','cust49@mail.com');
INSERT INTO Customer (CustomerName,Email) VALUES ('Customer 50','cust50@mail.com');
INSERT INTO Customer (CustomerName,Email) VALUES ('Customer 51','cust51@mail.com');
INSERT INTO Customer (CustomerName,Email) VALUES ('Customer 52','cust52@mail.com');
INSERT INTO Customer (CustomerName,Email) VALUES ('Customer 53','cust53@mail.com');
INSERT INTO Customer (CustomerName,Email) VALUES ('Customer 54','cust54@mail.com');
INSERT INTO Customer (CustomerName,Email) VALUES ('Customer 55','cust55@mail.com');
INSERT INTO Customer (CustomerName,Email) VALUES ('Customer 56','cust56@mail.com');
INSERT INTO Customer (CustomerName,Email) VALUES ('Customer 57','cust57@mail.com');
INSERT INTO Customer (CustomerName,Email) VALUES ('Customer 58','cust58@mail.com');
INSERT INTO Customer (CustomerName,Email) VALUES ('Customer 59','cust59@mail.com');
INSERT INTO Customer (CustomerName,Email) VALUES ('Customer 60','cust60@mail.com');
INSERT INTO Ticket (ShowtimeID,SeatNumber,CustomerID,Discount,Price,Status) VALUES (1,135,6,0,19,'ACTIVE');
INSERT INTO Ticket (ShowtimeID,SeatNumber,CustomerID,Discount,Price,Status) VALUES (65,50,51,0,15,'ACTIVE');
INSERT INTO Ticket (ShowtimeID,SeatNumber,CustomerID,Discount,Price,Status) VALUES (57,10,34,0,13,'ACTIVE');
INSERT INTO Ticket (ShowtimeID,SeatNumber,CustomerID,Discount,Price,Status) VALUES (70,120,58,0.2,18,'ACTIVE');
INSERT INTO Ticket (ShowtimeID,SeatNumber,CustomerID,Discount,Price,Status) VALUES (20,20,21,0.1,17,'ACTIVE');
INSERT INTO Ticket (ShowtimeID,SeatNumber,CustomerID,Discount,Price,Status) VALUES (18,123,38,0.1,15,'ACTIVE');
INSERT INTO Ticket (ShowtimeID,SeatNumber,CustomerID,Discount,Price,Status) VALUES (79,111,56,0,13,'ACTIVE');
INSERT INTO Ticket (ShowtimeID,SeatNumber,CustomerID,Discount,Price,Status) VALUES (51,102,30,0,12,'ACTIVE');
INSERT INTO Ticket (ShowtimeID,SeatNumber,CustomerID,Discount,Price,Status) VALUES (36,72,3,0,16,'ACTIVE');
INSERT INTO Ticket (ShowtimeID,SeatNumber,CustomerID,Discount,Price,Status) VALUES (33,31,26,0,16,'ACTIVE');
INSERT INTO Ticket (ShowtimeID,SeatNumber,CustomerID,Discount,Price,Status) VALUES (42,59,8,0,13,'ACTIVE');
INSERT INTO Ticket (ShowtimeID,SeatNumber,CustomerID,Discount,Price,Status) VALUES (26,91,52,0.2,12,'ACTIVE');
INSERT INTO Ticket (ShowtimeID,SeatNumber,CustomerID,Discount,Price,Status) VALUES (3,53,41,0,19,'ACTIVE');
INSERT INTO Ticket (ShowtimeID,SeatNumber,CustomerID,Discount,Price,Status) VALUES (20,142,31,0.2,16,'ACTIVE');
INSERT INTO Ticket (ShowtimeID,SeatNumber,CustomerID,Discount,Price,Status) VALUES (35,102,45,0.1,14,'ACTIVE');
INSERT INTO Ticket (ShowtimeID,SeatNumber,CustomerID,Discount,Price,Status) VALUES (77,104,2,0.2,15,'ACTIVE');
INSERT INTO Ticket (ShowtimeID,SeatNumber,CustomerID,Discount,Price,Status) VALUES (63,58,49,0.1,17,'ACTIVE');
INSERT INTO Ticket (ShowtimeID,SeatNumber,CustomerID,Discount,Price,Status) VALUES (17,26,57,0.1,18,'ACTIVE');
INSERT INTO Ticket (ShowtimeID,SeatNumber,CustomerID,Discount,Price,Status) VALUES (43,6,17,0.2,14,'ACTIVE');
INSERT INTO Ticket (ShowtimeID,SeatNumber,CustomerID,Discount,Price,Status) VALUES (14,91,2,0.2,14,'ACTIVE');
INSERT INTO Ticket (ShowtimeID,SeatNumber,CustomerID,Discount,Price,Status) VALUES (50,125,40,0,16,'ACTIVE');
INSERT INTO Ticket (ShowtimeID,SeatNumber,CustomerID,Discount,Price,Status) VALUES (77,49,40,0.2,12,'ACTIVE');
INSERT INTO Ticket (ShowtimeID,SeatNumber,CustomerID,Discount,Price,Status) VALUES (25,100,36,0.1,13,'ACTIVE');
INSERT INTO Ticket (ShowtimeID,SeatNumber,CustomerID,Discount,Price,Status) VALUES (63,32,38,0.1,16,'ACTIVE');
INSERT INTO Ticket (ShowtimeID,SeatNumber,CustomerID,Discount,Price,Status) VALUES (42,42,54,0,13,'ACTIVE');
INSERT INTO Ticket (ShowtimeID,SeatNumber,CustomerID,Discount,Price,Status) VALUES (17,69,16,0.1,15,'ACTIVE');
INSERT INTO Ticket (ShowtimeID,SeatNumber,CustomerID,Discount,Price,Status) VALUES (7,28,41,0.2,18,'ACTIVE');
INSERT INTO Ticket (ShowtimeID,SeatNumber,CustomerID,Discount,Price,Status) VALUES (69,71,16,0.1,18,'ACTIVE');
INSERT INTO Ticket (ShowtimeID,SeatNumber,CustomerID,Discount,Price,Status) VALUES (8,135,33,0,14,'ACTIVE');
INSERT INTO Ticket (ShowtimeID,SeatNumber,CustomerID,Discount,Price,Status) VALUES (66,121,59,0.1,19,'ACTIVE');
INSERT INTO Ticket (ShowtimeID,SeatNumber,CustomerID,Discount,Price,Status) VALUES (63,85,29,0.2,15,'ACTIVE');
INSERT INTO Ticket (ShowtimeID,SeatNumber,CustomerID,Discount,Price,Status) VALUES (69,37,51,0.2,14,'ACTIVE');
INSERT INTO Ticket (ShowtimeID,SeatNumber,CustomerID,Discount,Price,Status) VALUES (65,5,3,0.1,17,'ACTIVE');
INSERT INTO Ticket (ShowtimeID,SeatNumber,CustomerID,Discount,Price,Status) VALUES (40,34,59,0.1,12,'ACTIVE');
INSERT INTO Ticket (ShowtimeID,SeatNumber,CustomerID,Discount,Price,Status) VALUES (5,5,59,0,19,'ACTIVE');
INSERT INTO Ticket (ShowtimeID,SeatNumber,CustomerID,Discount,Price,Status) VALUES (48,72,21,0.1,15,'ACTIVE');
INSERT INTO Ticket (ShowtimeID,SeatNumber,CustomerID,Discount,Price,Status) VALUES (25,60,36,0.1,17,'ACTIVE');
INSERT INTO Ticket (ShowtimeID,SeatNumber,CustomerID,Discount,Price,Status) VALUES (41,16,60,0.1,15,'ACTIVE');
INSERT INTO Ticket (ShowtimeID,SeatNumber,CustomerID,Discount,Price,Status) VALUES (42,75,29,0,19,'ACTIVE');
INSERT INTO Ticket (ShowtimeID,SeatNumber,CustomerID,Discount,Price,Status) VALUES (6,131,28,0,14,'ACTIVE');
INSERT INTO Ticket (ShowtimeID,SeatNumber,CustomerID,Discount,Price,Status) VALUES (34,140,5,0,19,'ACTIVE');
INSERT INTO Ticket (ShowtimeID,SeatNumber,CustomerID,Discount,Price,Status) VALUES (20,11,35,0.1,12,'ACTIVE');
INSERT INTO Ticket (ShowtimeID,SeatNumber,CustomerID,Discount,Price,Status) VALUES (28,114,13,0.2,18,'ACTIVE');
INSERT INTO Ticket (ShowtimeID,SeatNumber,CustomerID,Discount,Price,Status) VALUES (26,143,30,0.1,18,'ACTIVE');
INSERT INTO Ticket (ShowtimeID,SeatNumber,CustomerID,Discount,Price,Status) VALUES (62,9,25,0,15,'ACTIVE');
INSERT INTO Ticket (ShowtimeID,SeatNumber,CustomerID,Discount,Price,Status) VALUES (9,77,19,0,16,'ACTIVE');
INSERT INTO Ticket (ShowtimeID,SeatNumber,CustomerID,Discount,Price,Status) VALUES (46,103,33,0,18,'ACTIVE');
INSERT INTO Ticket (ShowtimeID,SeatNumber,CustomerID,Discount,Price,Status) VALUES (79,7,18,0.1,13,'ACTIVE');
INSERT INTO Ticket (ShowtimeID,SeatNumber,CustomerID,Discount,Price,Status) VALUES (18,90,29,0.1,14,'ACTIVE');
INSERT INTO Ticket (ShowtimeID,SeatNumber,CustomerID,Discount,Price,Status) VALUES (58,120,20,0.1,14,'ACTIVE');
INSERT INTO Ticket (ShowtimeID,SeatNumber,CustomerID,Discount,Price,Status) VALUES (5,122,24,0,15,'ACTIVE');
INSERT INTO Ticket (ShowtimeID,SeatNumber,CustomerID,Discount,Price,Status) VALUES (68,70,11,0.2,19,'ACTIVE');
INSERT INTO Ticket (ShowtimeID,SeatNumber,CustomerID,Discount,Price,Status) VALUES (28,80,50,0.1,18,'ACTIVE');
INSERT INTO Ticket (ShowtimeID,SeatNumber,CustomerID,Discount,Price,Status) VALUES (27,89,57,0.1,13,'ACTIVE');
INSERT INTO Ticket (ShowtimeID,SeatNumber,CustomerID,Discount,Price,Status) VALUES (72,70,41,0.1,15,'ACTIVE');
INSERT INTO Ticket (ShowtimeID,SeatNumber,CustomerID,Discount,Price,Status) VALUES (31,132,11,0.2,19,'ACTIVE');
INSERT INTO Ticket (ShowtimeID,SeatNumber,CustomerID,Discount,Price,Status) VALUES (43,76,6,0.2,18,'ACTIVE');
INSERT INTO Ticket (ShowtimeID,SeatNumber,CustomerID,Discount,Price,Status) VALUES (18,103,1,0.2,19,'ACTIVE');
INSERT INTO Ticket (ShowtimeID,SeatNumber,CustomerID,Discount,Price,Status) VALUES (10,76,36,0.1,12,'ACTIVE');
INSERT INTO Ticket (ShowtimeID,SeatNumber,CustomerID,Discount,Price,Status) VALUES (47,22,23,0.1,14,'ACTIVE');
INSERT INTO Ticket (ShowtimeID,SeatNumber,CustomerID,Discount,Price,Status) VALUES (15,143,59,0.2,12,'ACTIVE');
INSERT INTO Ticket (ShowtimeID,SeatNumber,CustomerID,Discount,Price,Status) VALUES (64,105,30,0,13,'ACTIVE');
INSERT INTO Ticket (ShowtimeID,SeatNumber,CustomerID,Discount,Price,Status) VALUES (69,56,26,0.1,18,'ACTIVE');
INSERT INTO Ticket (ShowtimeID,SeatNumber,CustomerID,Discount,Price,Status) VALUES (42,117,37,0.2,17,'ACTIVE');
INSERT INTO Ticket (ShowtimeID,SeatNumber,CustomerID,Discount,Price,Status) VALUES (58,112,52,0.2,12,'ACTIVE');
INSERT INTO Ticket (ShowtimeID,SeatNumber,CustomerID,Discount,Price,Status) VALUES (44,86,35,0.1,19,'ACTIVE');
INSERT INTO Ticket (ShowtimeID,SeatNumber,CustomerID,Discount,Price,Status) VALUES (8,62,43,0,19,'ACTIVE');
INSERT INTO Ticket (ShowtimeID,SeatNumber,CustomerID,Discount,Price,Status) VALUES (70,105,35,0.1,19,'ACTIVE');
INSERT INTO Ticket (ShowtimeID,SeatNumber,CustomerID,Discount,Price,Status) VALUES (51,133,26,0,17,'ACTIVE');
INSERT INTO Ticket (ShowtimeID,SeatNumber,CustomerID,Discount,Price,Status) VALUES (47,53,43,0,16,'ACTIVE');
INSERT INTO Ticket (ShowtimeID,SeatNumber,CustomerID,Discount,Price,Status) VALUES (61,29,54,0,15,'ACTIVE');
INSERT INTO Ticket (ShowtimeID,SeatNumber,CustomerID,Discount,Price,Status) VALUES (66,68,43,0.1,18,'ACTIVE');
INSERT INTO Ticket (ShowtimeID,SeatNumber,CustomerID,Discount,Price,Status) VALUES (31,116,33,0.2,13,'ACTIVE');
INSERT INTO Ticket (ShowtimeID,SeatNumber,CustomerID,Discount,Price,Status) VALUES (51,93,43,0,17,'ACTIVE');
INSERT INTO Ticket (ShowtimeID,SeatNumber,CustomerID,Discount,Price,Status) VALUES (69,13,41,0.2,13,'ACTIVE');
INSERT INTO Ticket (ShowtimeID,SeatNumber,CustomerID,Discount,Price,Status) VALUES (12,81,15,0,19,'ACTIVE');
INSERT INTO Ticket (ShowtimeID,SeatNumber,CustomerID,Discount,Price,Status) VALUES (56,125,9,0.2,16,'ACTIVE');
INSERT INTO Ticket (ShowtimeID,SeatNumber,CustomerID,Discount,Price,Status) VALUES (39,144,20,0.1,14,'ACTIVE');
INSERT INTO Ticket (ShowtimeID,SeatNumber,CustomerID,Discount,Price,Status) VALUES (58,80,15,0.2,12,'ACTIVE');
INSERT INTO Ticket (ShowtimeID,SeatNumber,CustomerID,Discount,Price,Status) VALUES (34,100,2,0,18,'ACTIVE');
INSERT INTO Ticket (ShowtimeID,SeatNumber,CustomerID,Discount,Price,Status) VALUES (16,98,1,0,18,'ACTIVE');
INSERT INTO Ticket (ShowtimeID,SeatNumber,CustomerID,Discount,Price,Status) VALUES (46,121,50,0.2,15,'ACTIVE');
INSERT INTO Ticket (ShowtimeID,SeatNumber,CustomerID,Discount,Price,Status) VALUES (22,92,1,0.1,16,'ACTIVE');
INSERT INTO Ticket (ShowtimeID,SeatNumber,CustomerID,Discount,Price,Status) VALUES (8,92,27,0.1,19,'ACTIVE');
INSERT INTO Ticket (ShowtimeID,SeatNumber,CustomerID,Discount,Price,Status) VALUES (39,47,50,0.1,17,'ACTIVE');
INSERT INTO Ticket (ShowtimeID,SeatNumber,CustomerID,Discount,Price,Status) VALUES (59,137,1,0.2,13,'ACTIVE');
INSERT INTO Ticket (ShowtimeID,SeatNumber,CustomerID,Discount,Price,Status) VALUES (4,46,25,0.2,13,'ACTIVE');
INSERT INTO Ticket (ShowtimeID,SeatNumber,CustomerID,Discount,Price,Status) VALUES (59,141,13,0.2,17,'ACTIVE');
INSERT INTO Ticket (ShowtimeID,SeatNumber,CustomerID,Discount,Price,Status) VALUES (58,82,46,0.2,19,'ACTIVE');
INSERT INTO Ticket (ShowtimeID,SeatNumber,CustomerID,Discount,Price,Status) VALUES (76,49,10,0,14,'ACTIVE');
INSERT INTO Ticket (ShowtimeID,SeatNumber,CustomerID,Discount,Price,Status) VALUES (28,10,33,0.2,12,'ACTIVE');
INSERT INTO Ticket (ShowtimeID,SeatNumber,CustomerID,Discount,Price,Status) VALUES (36,70,46,0.1,12,'ACTIVE');
INSERT INTO Ticket (ShowtimeID,SeatNumber,CustomerID,Discount,Price,Status) VALUES (53,19,52,0.1,19,'ACTIVE');
INSERT INTO Ticket (ShowtimeID,SeatNumber,CustomerID,Discount,Price,Status) VALUES (67,144,51,0.1,19,'ACTIVE');
INSERT INTO Ticket (ShowtimeID,SeatNumber,CustomerID,Discount,Price,Status) VALUES (29,35,9,0,18,'ACTIVE');
INSERT INTO Ticket (ShowtimeID,SeatNumber,CustomerID,Discount,Price,Status) VALUES (61,5,19,0.2,18,'ACTIVE');
INSERT INTO Ticket (ShowtimeID,SeatNumber,CustomerID,Discount,Price,Status) VALUES (5,85,32,0,14,'ACTIVE');
INSERT INTO Ticket (ShowtimeID,SeatNumber,CustomerID,Discount,Price,Status) VALUES (75,117,18,0.1,19,'ACTIVE');
INSERT INTO Ticket (ShowtimeID,SeatNumber,CustomerID,Discount,Price,Status) VALUES (59,67,35,0,13,'ACTIVE');
INSERT INTO Ticket (ShowtimeID,SeatNumber,CustomerID,Discount,Price,Status) VALUES (66,84,31,0,17,'ACTIVE');
INSERT INTO Ticket (ShowtimeID,SeatNumber,CustomerID,Discount,Price,Status) VALUES (39,84,5,0.1,17,'ACTIVE');
INSERT INTO Ticket (ShowtimeID,SeatNumber,CustomerID,Discount,Price,Status) VALUES (55,115,43,0.2,18,'ACTIVE');
INSERT INTO Ticket (ShowtimeID,SeatNumber,CustomerID,Discount,Price,Status) VALUES (59,138,14,0,19,'ACTIVE');
INSERT INTO Ticket (ShowtimeID,SeatNumber,CustomerID,Discount,Price,Status) VALUES (42,61,39,0.1,18,'ACTIVE');
INSERT INTO Ticket (ShowtimeID,SeatNumber,CustomerID,Discount,Price,Status) VALUES (38,101,9,0,13,'ACTIVE');
INSERT INTO Ticket (ShowtimeID,SeatNumber,CustomerID,Discount,Price,Status) VALUES (8,28,29,0.1,12,'ACTIVE');
INSERT INTO Ticket (ShowtimeID,SeatNumber,CustomerID,Discount,Price,Status) VALUES (41,19,53,0.1,12,'ACTIVE');
INSERT INTO Ticket (ShowtimeID,SeatNumber,CustomerID,Discount,Price,Status) VALUES (34,107,12,0.1,16,'ACTIVE');
INSERT INTO Ticket (ShowtimeID,SeatNumber,CustomerID,Discount,Price,Status) VALUES (71,83,7,0.2,12,'ACTIVE');
INSERT INTO Ticket (ShowtimeID,SeatNumber,CustomerID,Discount,Price,Status) VALUES (10,96,28,0,16,'ACTIVE');
INSERT INTO Ticket (ShowtimeID,SeatNumber,CustomerID,Discount,Price,Status) VALUES (15,76,51,0,12,'ACTIVE');
INSERT INTO Ticket (ShowtimeID,SeatNumber,CustomerID,Discount,Price,Status) VALUES (73,55,29,0,17,'ACTIVE');
INSERT INTO Ticket (ShowtimeID,SeatNumber,CustomerID,Discount,Price,Status) VALUES (8,137,29,0,18,'ACTIVE');
INSERT INTO Ticket (ShowtimeID,SeatNumber,CustomerID,Discount,Price,Status) VALUES (80,78,52,0.2,12,'ACTIVE');
INSERT INTO Ticket (ShowtimeID,SeatNumber,CustomerID,Discount,Price,Status) VALUES (26,130,35,0.1,19,'ACTIVE');
INSERT INTO Ticket (ShowtimeID,SeatNumber,CustomerID,Discount,Price,Status) VALUES (66,132,18,0.2,14,'ACTIVE');
INSERT INTO Ticket (ShowtimeID,SeatNumber,CustomerID,Discount,Price,Status) VALUES (60,41,23,0,18,'ACTIVE');
INSERT INTO Ticket (ShowtimeID,SeatNumber,CustomerID,Discount,Price,Status) VALUES (1,134,19,0.2,19,'ACTIVE');
INSERT INTO Ticket (ShowtimeID,SeatNumber,CustomerID,Discount,Price,Status) VALUES (30,53,24,0,13,'ACTIVE');
INSERT INTO Ticket (ShowtimeID,SeatNumber,CustomerID,Discount,Price,Status) VALUES (5,129,47,0.2,16,'ACTIVE');
INSERT INTO Ticket (ShowtimeID,SeatNumber,CustomerID,Discount,Price,Status) VALUES (27,106,11,0.2,12,'ACTIVE');
INSERT INTO Ticket (ShowtimeID,SeatNumber,CustomerID,Discount,Price,Status) VALUES (77,80,24,0.1,16,'ACTIVE');
INSERT INTO Ticket (ShowtimeID,SeatNumber,CustomerID,Discount,Price,Status) VALUES (74,65,13,0,16,'ACTIVE');
INSERT INTO Ticket (ShowtimeID,SeatNumber,CustomerID,Discount,Price,Status) VALUES (72,17,53,0.2,15,'ACTIVE');
INSERT INTO Ticket (ShowtimeID,SeatNumber,CustomerID,Discount,Price,Status) VALUES (62,86,56,0.2,16,'ACTIVE');
INSERT INTO Ticket (ShowtimeID,SeatNumber,CustomerID,Discount,Price,Status) VALUES (67,98,39,0.1,14,'ACTIVE');
INSERT INTO Ticket (ShowtimeID,SeatNumber,CustomerID,Discount,Price,Status) VALUES (51,75,39,0,12,'ACTIVE');
INSERT INTO Ticket (ShowtimeID,SeatNumber,CustomerID,Discount,Price,Status) VALUES (11,65,50,0.2,16,'ACTIVE');
INSERT INTO Ticket (ShowtimeID,SeatNumber,CustomerID,Discount,Price,Status) VALUES (71,43,47,0.1,17,'ACTIVE');
INSERT INTO Ticket (ShowtimeID,SeatNumber,CustomerID,Discount,Price,Status) VALUES (68,43,24,0.1,13,'ACTIVE');
INSERT INTO Ticket (ShowtimeID,SeatNumber,CustomerID,Discount,Price,Status) VALUES (60,76,36,0.2,18,'ACTIVE');
INSERT INTO Ticket (ShowtimeID,SeatNumber,CustomerID,Discount,Price,Status) VALUES (6,104,6,0.1,17,'ACTIVE');
INSERT INTO Ticket (ShowtimeID,SeatNumber,CustomerID,Discount,Price,Status) VALUES (19,107,37,0.2,13,'ACTIVE');
INSERT INTO Ticket (ShowtimeID,SeatNumber,CustomerID,Discount,Price,Status) VALUES (41,98,60,0,12,'ACTIVE');
INSERT INTO Ticket (ShowtimeID,SeatNumber,CustomerID,Discount,Price,Status) VALUES (36,102,39,0.1,13,'ACTIVE');
INSERT INTO Ticket (ShowtimeID,SeatNumber,CustomerID,Discount,Price,Status) VALUES (24,41,48,0,13,'ACTIVE');
INSERT INTO Ticket (ShowtimeID,SeatNumber,CustomerID,Discount,Price,Status) VALUES (50,71,36,0.2,16,'ACTIVE');
INSERT INTO Ticket (ShowtimeID,SeatNumber,CustomerID,Discount,Price,Status) VALUES (66,96,9,0,12,'ACTIVE');
INSERT INTO Ticket (ShowtimeID,SeatNumber,CustomerID,Discount,Price,Status) VALUES (33,50,53,0.1,16,'ACTIVE');
INSERT INTO Ticket (ShowtimeID,SeatNumber,CustomerID,Discount,Price,Status) VALUES (12,89,16,0.2,17,'ACTIVE');
INSERT INTO Ticket (ShowtimeID,SeatNumber,CustomerID,Discount,Price,Status) VALUES (4,6,33,0.2,16,'ACTIVE');
INSERT INTO Ticket (ShowtimeID,SeatNumber,CustomerID,Discount,Price,Status) VALUES (31,34,32,0.2,17,'ACTIVE');
INSERT INTO Ticket (ShowtimeID,SeatNumber,CustomerID,Discount,Price,Status) VALUES (30,116,14,0.1,13,'ACTIVE');
INSERT INTO Ticket (ShowtimeID,SeatNumber,CustomerID,Discount,Price,Status) VALUES (63,108,31,0.1,19,'ACTIVE');
INSERT INTO Ticket (ShowtimeID,SeatNumber,CustomerID,Discount,Price,Status) VALUES (59,79,14,0.2,18,'ACTIVE');
INSERT INTO Ticket (ShowtimeID,SeatNumber,CustomerID,Discount,Price,Status) VALUES (10,26,26,0.2,13,'ACTIVE');
INSERT INTO Ticket (ShowtimeID,SeatNumber,CustomerID,Discount,Price,Status) VALUES (19,125,57,0,18,'ACTIVE');
INSERT INTO Ticket (ShowtimeID,SeatNumber,CustomerID,Discount,Price,Status) VALUES (57,56,6,0.1,14,'ACTIVE');
INSERT INTO Ticket (ShowtimeID,SeatNumber,CustomerID,Discount,Price,Status) VALUES (69,113,34,0.1,18,'ACTIVE');
INSERT INTO Ticket (ShowtimeID,SeatNumber,CustomerID,Discount,Price,Status) VALUES (33,3,30,0.2,16,'ACTIVE');
INSERT INTO Ticket (ShowtimeID,SeatNumber,CustomerID,Discount,Price,Status) VALUES (74,136,6,0.1,19,'ACTIVE');
INSERT INTO Ticket (ShowtimeID,SeatNumber,CustomerID,Discount,Price,Status) VALUES (19,113,6,0.2,15,'ACTIVE');
INSERT INTO Ticket (ShowtimeID,SeatNumber,CustomerID,Discount,Price,Status) VALUES (48,60,9,0.1,19,'ACTIVE');
INSERT INTO Ticket (ShowtimeID,SeatNumber,CustomerID,Discount,Price,Status) VALUES (60,39,43,0,18,'ACTIVE');
INSERT INTO Ticket (ShowtimeID,SeatNumber,CustomerID,Discount,Price,Status) VALUES (43,139,59,0.1,16,'ACTIVE');
INSERT INTO Ticket (ShowtimeID,SeatNumber,CustomerID,Discount,Price,Status) VALUES (12,40,11,0.1,19,'ACTIVE');
INSERT INTO Ticket (ShowtimeID,SeatNumber,CustomerID,Discount,Price,Status) VALUES (34,28,8,0.2,12,'ACTIVE');
INSERT INTO Ticket (ShowtimeID,SeatNumber,CustomerID,Discount,Price,Status) VALUES (71,57,17,0,15,'ACTIVE');
INSERT INTO Ticket (ShowtimeID,SeatNumber,CustomerID,Discount,Price,Status) VALUES (57,22,13,0,19,'ACTIVE');
INSERT INTO Ticket (ShowtimeID,SeatNumber,CustomerID,Discount,Price,Status) VALUES (10,12,58,0.2,17,'ACTIVE');
INSERT INTO Ticket (ShowtimeID,SeatNumber,CustomerID,Discount,Price,Status) VALUES (19,64,34,0.2,17,'ACTIVE');
INSERT INTO Ticket (ShowtimeID,SeatNumber,CustomerID,Discount,Price,Status) VALUES (45,96,31,0.1,12,'ACTIVE');
INSERT INTO Ticket (ShowtimeID,SeatNumber,CustomerID,Discount,Price,Status) VALUES (36,78,10,0.2,14,'ACTIVE');
INSERT INTO Ticket (ShowtimeID,SeatNumber,CustomerID,Discount,Price,Status) VALUES (59,132,6,0.1,18,'ACTIVE');
INSERT INTO Ticket (ShowtimeID,SeatNumber,CustomerID,Discount,Price,Status) VALUES (68,119,28,0.2,14,'ACTIVE');
INSERT INTO Ticket (ShowtimeID,SeatNumber,CustomerID,Discount,Price,Status) VALUES (56,30,30,0.1,13,'ACTIVE');
INSERT INTO Ticket (ShowtimeID,SeatNumber,CustomerID,Discount,Price,Status) VALUES (10,78,58,0,17,'ACTIVE');
INSERT INTO Ticket (ShowtimeID,SeatNumber,CustomerID,Discount,Price,Status) VALUES (3,91,47,0.1,14,'ACTIVE');
INSERT INTO Ticket (ShowtimeID,SeatNumber,CustomerID,Discount,Price,Status) VALUES (61,119,52,0.2,13,'ACTIVE');
INSERT INTO Ticket (ShowtimeID,SeatNumber,CustomerID,Discount,Price,Status) VALUES (12,7,6,0.1,12,'ACTIVE');
INSERT INTO Ticket (ShowtimeID,SeatNumber,CustomerID,Discount,Price,Status) VALUES (20,20,54,0,14,'ACTIVE');
INSERT INTO Ticket (ShowtimeID,SeatNumber,CustomerID,Discount,Price,Status) VALUES (29,105,9,0,17,'ACTIVE');
INSERT INTO Ticket (ShowtimeID,SeatNumber,CustomerID,Discount,Price,Status) VALUES (45,40,10,0.1,15,'ACTIVE');
INSERT INTO Ticket (ShowtimeID,SeatNumber,CustomerID,Discount,Price,Status) VALUES (15,131,6,0.2,14,'ACTIVE');
INSERT INTO Ticket (ShowtimeID,SeatNumber,CustomerID,Discount,Price,Status) VALUES (48,69,26,0,14,'ACTIVE');
INSERT INTO Ticket (ShowtimeID,SeatNumber,CustomerID,Discount,Price,Status) VALUES (12,80,43,0,17,'ACTIVE');
INSERT INTO Ticket (ShowtimeID,SeatNumber,CustomerID,Discount,Price,Status) VALUES (54,144,2,0.1,17,'ACTIVE');
INSERT INTO Ticket (ShowtimeID,SeatNumber,CustomerID,Discount,Price,Status) VALUES (8,1,51,0.1,13,'ACTIVE');
INSERT INTO Ticket (ShowtimeID,SeatNumber,CustomerID,Discount,Price,Status) VALUES (44,51,54,0.2,14,'ACTIVE');
INSERT INTO Ticket (ShowtimeID,SeatNumber,CustomerID,Discount,Price,Status) VALUES (15,8,46,0.2,17,'ACTIVE');
INSERT INTO Ticket (ShowtimeID,SeatNumber,CustomerID,Discount,Price,Status) VALUES (69,105,22,0.2,15,'ACTIVE');
INSERT INTO Ticket (ShowtimeID,SeatNumber,CustomerID,Discount,Price,Status) VALUES (47,102,45,0.1,12,'ACTIVE');
INSERT INTO Ticket (ShowtimeID,SeatNumber,CustomerID,Discount,Price,Status) VALUES (37,36,57,0.2,12,'ACTIVE');
INSERT INTO Ticket (ShowtimeID,SeatNumber,CustomerID,Discount,Price,Status) VALUES (15,6,16,0.1,15,'ACTIVE');
INSERT INTO Ticket (ShowtimeID,SeatNumber,CustomerID,Discount,Price,Status) VALUES (56,90,45,0,13,'ACTIVE');
INSERT INTO Ticket (ShowtimeID,SeatNumber,CustomerID,Discount,Price,Status) VALUES (36,80,44,0,19,'ACTIVE');
INSERT INTO Ticket (ShowtimeID,SeatNumber,CustomerID,Discount,Price,Status) VALUES (25,27,44,0,19,'ACTIVE');
INSERT INTO Ticket (ShowtimeID,SeatNumber,CustomerID,Discount,Price,Status) VALUES (47,20,17,0,18,'ACTIVE');
INSERT INTO Ticket (ShowtimeID,SeatNumber,CustomerID,Discount,Price,Status) VALUES (72,100,43,0.2,17,'ACTIVE');
INSERT INTO Ticket (ShowtimeID,SeatNumber,CustomerID,Discount,Price,Status) VALUES (28,53,30,0,15,'ACTIVE');
INSERT INTO Ticket (ShowtimeID,SeatNumber,CustomerID,Discount,Price,Status) VALUES (63,22,60,0,19,'ACTIVE');
INSERT INTO Ticket (ShowtimeID,SeatNumber,CustomerID,Discount,Price,Status) VALUES (14,98,59,0.2,17,'ACTIVE');
INSERT INTO Ticket (ShowtimeID,SeatNumber,CustomerID,Discount,Price,Status) VALUES (59,40,39,0.2,13,'ACTIVE');
INSERT INTO Ticket (ShowtimeID,SeatNumber,CustomerID,Discount,Price,Status) VALUES (12,5,44,0.1,17,'ACTIVE');
INSERT INTO Ticket (ShowtimeID,SeatNumber,CustomerID,Discount,Price,Status) VALUES (39,73,39,0.1,16,'ACTIVE');
INSERT INTO Ticket (ShowtimeID,SeatNumber,CustomerID,Discount,Price,Status) VALUES (34,37,14,0,18,'ACTIVE');
INSERT INTO Ticket (ShowtimeID,SeatNumber,CustomerID,Discount,Price,Status) VALUES (45,48,53,0,12,'ACTIVE');
INSERT INTO Ticket (ShowtimeID,SeatNumber,CustomerID,Discount,Price,Status) VALUES (37,55,36,0.2,13,'ACTIVE');
INSERT INTO Ticket (ShowtimeID,SeatNumber,CustomerID,Discount,Price,Status) VALUES (48,36,35,0,14,'ACTIVE');
INSERT INTO Ticket (ShowtimeID,SeatNumber,CustomerID,Discount,Price,Status) VALUES (30,85,5,0.1,13,'ACTIVE');
INSERT INTO Ticket (ShowtimeID,SeatNumber,CustomerID,Discount,Price,Status) VALUES (77,137,52,0.1,12,'ACTIVE');
INSERT INTO Ticket (ShowtimeID,SeatNumber,CustomerID,Discount,Price,Status) VALUES (10,113,6,0.1,15,'ACTIVE');
INSERT INTO Ticket (ShowtimeID,SeatNumber,CustomerID,Discount,Price,Status) VALUES (61,138,14,0.2,14,'ACTIVE');
INSERT INTO Ticket (ShowtimeID,SeatNumber,CustomerID,Discount,Price,Status) VALUES (30,110,18,0,12,'ACTIVE');
INSERT INTO Ticket (ShowtimeID,SeatNumber,CustomerID,Discount,Price,Status) VALUES (67,21,55,0.1,13,'ACTIVE');
INSERT INTO Ticket (ShowtimeID,SeatNumber,CustomerID,Discount,Price,Status) VALUES (5,77,42,0.1,15,'ACTIVE');
INSERT INTO Ticket (ShowtimeID,SeatNumber,CustomerID,Discount,Price,Status) VALUES (67,12,28,0.2,12,'ACTIVE');
INSERT INTO Ticket (ShowtimeID,SeatNumber,CustomerID,Discount,Price,Status) VALUES (79,42,36,0.1,16,'ACTIVE');
INSERT INTO Ticket (ShowtimeID,SeatNumber,CustomerID,Discount,Price,Status) VALUES (61,108,41,0.1,19,'ACTIVE');
INSERT INTO Ticket (ShowtimeID,SeatNumber,CustomerID,Discount,Price,Status) VALUES (32,6,49,0.1,16,'ACTIVE');
INSERT INTO Ticket (ShowtimeID,SeatNumber,CustomerID,Discount,Price,Status) VALUES (35,135,34,0.2,14,'ACTIVE');
INSERT INTO Ticket (ShowtimeID,SeatNumber,CustomerID,Discount,Price,Status) VALUES (8,3,50,0,15,'ACTIVE');
INSERT INTO Ticket (ShowtimeID,SeatNumber,CustomerID,Discount,Price,Status) VALUES (45,71,54,0.2,18,'ACTIVE');
INSERT INTO Ticket (ShowtimeID,SeatNumber,CustomerID,Discount,Price,Status) VALUES (65,76,54,0,16,'ACTIVE');
INSERT INTO Ticket (ShowtimeID,SeatNumber,CustomerID,Discount,Price,Status) VALUES (53,110,32,0.2,17,'ACTIVE');
INSERT INTO Ticket (ShowtimeID,SeatNumber,CustomerID,Discount,Price,Status) VALUES (63,49,3,0.2,12,'ACTIVE');
INSERT INTO Ticket (ShowtimeID,SeatNumber,CustomerID,Discount,Price,Status) VALUES (56,118,44,0.1,17,'ACTIVE');
INSERT INTO Ticket (ShowtimeID,SeatNumber,CustomerID,Discount,Price,Status) VALUES (27,109,15,0.1,12,'ACTIVE');
INSERT INTO Ticket (ShowtimeID,SeatNumber,CustomerID,Discount,Price,Status) VALUES (48,5,29,0.1,18,'ACTIVE');
INSERT INTO Ticket (ShowtimeID,SeatNumber,CustomerID,Discount,Price,Status) VALUES (25,28,29,0,16,'ACTIVE');
INSERT INTO Ticket (ShowtimeID,SeatNumber,CustomerID,Discount,Price,Status) VALUES (73,67,1,0,14,'ACTIVE');
INSERT INTO Ticket (ShowtimeID,SeatNumber,CustomerID,Discount,Price,Status) VALUES (39,95,12,0.2,16,'ACTIVE');
INSERT INTO Ticket (ShowtimeID,SeatNumber,CustomerID,Discount,Price,Status) VALUES (59,48,3,0,17,'ACTIVE');
INSERT INTO Ticket (ShowtimeID,SeatNumber,CustomerID,Discount,Price,Status) VALUES (74,9,53,0.1,16,'ACTIVE');
INSERT INTO Ticket (ShowtimeID,SeatNumber,CustomerID,Discount,Price,Status) VALUES (42,53,58,0.2,12,'ACTIVE');
INSERT INTO Ticket (ShowtimeID,SeatNumber,CustomerID,Discount,Price,Status) VALUES (7,65,24,0.1,12,'ACTIVE');
INSERT INTO Ticket (ShowtimeID,SeatNumber,CustomerID,Discount,Price,Status) VALUES (57,129,56,0,17,'ACTIVE');
INSERT INTO Ticket (ShowtimeID,SeatNumber,CustomerID,Discount,Price,Status) VALUES (30,103,43,0.2,13,'ACTIVE');
INSERT INTO Ticket (ShowtimeID,SeatNumber,CustomerID,Discount,Price,Status) VALUES (80,81,6,0,17,'ACTIVE');
INSERT INTO Ticket (ShowtimeID,SeatNumber,CustomerID,Discount,Price,Status) VALUES (71,134,19,0.1,13,'ACTIVE');
INSERT INTO Ticket (ShowtimeID,SeatNumber,CustomerID,Discount,Price,Status) VALUES (42,101,19,0.1,17,'ACTIVE');
INSERT INTO Ticket (ShowtimeID,SeatNumber,CustomerID,Discount,Price,Status) VALUES (26,8,19,0,12,'ACTIVE');
INSERT INTO Ticket (ShowtimeID,SeatNumber,CustomerID,Discount,Price,Status) VALUES (49,127,31,0.2,14,'ACTIVE');
INSERT INTO Ticket (ShowtimeID,SeatNumber,CustomerID,Discount,Price,Status) VALUES (20,107,57,0.1,19,'ACTIVE');
INSERT INTO Ticket (ShowtimeID,SeatNumber,CustomerID,Discount,Price,Status) VALUES (22,16,34,0,19,'ACTIVE');
INSERT INTO Ticket (ShowtimeID,SeatNumber,CustomerID,Discount,Price,Status) VALUES (73,128,37,0,13,'ACTIVE');
INSERT INTO Ticket (ShowtimeID,SeatNumber,CustomerID,Discount,Price,Status) VALUES (40,93,8,0,15,'ACTIVE');
INSERT INTO Ticket (ShowtimeID,SeatNumber,CustomerID,Discount,Price,Status) VALUES (6,6,30,0.2,12,'ACTIVE');
INSERT INTO Ticket (ShowtimeID,SeatNumber,CustomerID,Discount,Price,Status) VALUES (35,67,32,0.2,15,'ACTIVE');
INSERT INTO Ticket (ShowtimeID,SeatNumber,CustomerID,Discount,Price,Status) VALUES (41,52,44,0.2,16,'ACTIVE');
INSERT INTO Ticket (ShowtimeID,SeatNumber,CustomerID,Discount,Price,Status) VALUES (17,125,10,0.2,15,'ACTIVE');
INSERT INTO Ticket (ShowtimeID,SeatNumber,CustomerID,Discount,Price,Status) VALUES (55,58,37,0.2,17,'ACTIVE');
INSERT INTO Ticket (ShowtimeID,SeatNumber,CustomerID,Discount,Price,Status) VALUES (77,84,46,0.1,14,'ACTIVE');
INSERT INTO Ticket (ShowtimeID,SeatNumber,CustomerID,Discount,Price,Status) VALUES (37,25,41,0,19,'ACTIVE');
INSERT INTO Ticket (ShowtimeID,SeatNumber,CustomerID,Discount,Price,Status) VALUES (62,26,34,0,17,'ACTIVE');
INSERT INTO Ticket (ShowtimeID,SeatNumber,CustomerID,Discount,Price,Status) VALUES (52,52,26,0.2,12,'ACTIVE');
INSERT INTO Ticket (ShowtimeID,SeatNumber,CustomerID,Discount,Price,Status) VALUES (74,91,47,0,14,'ACTIVE');
INSERT INTO Ticket (ShowtimeID,SeatNumber,CustomerID,Discount,Price,Status) VALUES (51,71,55,0.2,16,'ACTIVE');
INSERT INTO Ticket (ShowtimeID,SeatNumber,CustomerID,Discount,Price,Status) VALUES (55,66,49,0.1,19,'ACTIVE');
INSERT INTO Ticket (ShowtimeID,SeatNumber,CustomerID,Discount,Price,Status) VALUES (64,122,47,0.1,14,'ACTIVE');
INSERT INTO Ticket (ShowtimeID,SeatNumber,CustomerID,Discount,Price,Status) VALUES (71,42,44,0.1,14,'ACTIVE');
INSERT INTO Ticket (ShowtimeID,SeatNumber,CustomerID,Discount,Price,Status) VALUES (33,135,53,0,14,'ACTIVE');
INSERT INTO Ticket (ShowtimeID,SeatNumber,CustomerID,Discount,Price,Status) VALUES (18,62,6,0,15,'ACTIVE');
INSERT INTO Ticket (ShowtimeID,SeatNumber,CustomerID,Discount,Price,Status) VALUES (66,9,28,0.2,18,'ACTIVE');
INSERT INTO Ticket (ShowtimeID,SeatNumber,CustomerID,Discount,Price,Status) VALUES (47,104,48,0.1,16,'ACTIVE');
INSERT INTO Ticket (ShowtimeID,SeatNumber,CustomerID,Discount,Price,Status) VALUES (21,7,12,0,18,'ACTIVE');
INSERT INTO Ticket (ShowtimeID,SeatNumber,CustomerID,Discount,Price,Status) VALUES (63,48,29,0.2,12,'ACTIVE');
INSERT INTO Ticket (ShowtimeID,SeatNumber,CustomerID,Discount,Price,Status) VALUES (21,27,33,0,16,'ACTIVE');
INSERT INTO Ticket (ShowtimeID,SeatNumber,CustomerID,Discount,Price,Status) VALUES (53,42,32,0.1,14,'ACTIVE');
INSERT INTO Ticket (ShowtimeID,SeatNumber,CustomerID,Discount,Price,Status) VALUES (74,28,45,0,15,'ACTIVE');
INSERT INTO Ticket (ShowtimeID,SeatNumber,CustomerID,Discount,Price,Status) VALUES (66,56,34,0.2,18,'ACTIVE');
INSERT INTO Ticket (ShowtimeID,SeatNumber,CustomerID,Discount,Price,Status) VALUES (13,53,46,0,12,'ACTIVE');
INSERT INTO Ticket (ShowtimeID,SeatNumber,CustomerID,Discount,Price,Status) VALUES (66,129,55,0.1,17,'ACTIVE');
INSERT INTO Ticket (ShowtimeID,SeatNumber,CustomerID,Discount,Price,Status) VALUES (11,73,24,0.2,12,'ACTIVE');
INSERT INTO Ticket (ShowtimeID,SeatNumber,CustomerID,Discount,Price,Status) VALUES (74,57,40,0.1,12,'ACTIVE');
INSERT INTO Ticket (ShowtimeID,SeatNumber,CustomerID,Discount,Price,Status) VALUES (24,118,39,0,12,'ACTIVE');
INSERT INTO Ticket (ShowtimeID,SeatNumber,CustomerID,Discount,Price,Status) VALUES (8,31,40,0,14,'ACTIVE');
INSERT INTO Ticket (ShowtimeID,SeatNumber,CustomerID,Discount,Price,Status) VALUES (54,114,9,0.1,12,'ACTIVE');
INSERT INTO Ticket (ShowtimeID,SeatNumber,CustomerID,Discount,Price,Status) VALUES (75,20,8,0.2,19,'ACTIVE');
INSERT INTO Ticket (ShowtimeID,SeatNumber,CustomerID,Discount,Price,Status) VALUES (44,70,52,0.1,19,'ACTIVE');
INSERT INTO Ticket (ShowtimeID,SeatNumber,CustomerID,Discount,Price,Status) VALUES (42,108,9,0.2,16,'ACTIVE');
INSERT INTO Ticket (ShowtimeID,SeatNumber,CustomerID,Discount,Price,Status) VALUES (23,130,39,0.2,13,'ACTIVE');
INSERT INTO Ticket (ShowtimeID,SeatNumber,CustomerID,Discount,Price,Status) VALUES (74,17,14,0,17,'ACTIVE');
INSERT INTO Ticket (ShowtimeID,SeatNumber,CustomerID,Discount,Price,Status) VALUES (12,142,46,0,19,'ACTIVE');
INSERT INTO Ticket (ShowtimeID,SeatNumber,CustomerID,Discount,Price,Status) VALUES (28,119,35,0.1,16,'ACTIVE');
INSERT INTO Ticket (ShowtimeID,SeatNumber,CustomerID,Discount,Price,Status) VALUES (32,49,33,0,15,'ACTIVE');
INSERT INTO Ticket (ShowtimeID,SeatNumber,CustomerID,Discount,Price,Status) VALUES (34,79,5,0,14,'ACTIVE');
INSERT INTO Ticket (ShowtimeID,SeatNumber,CustomerID,Discount,Price,Status) VALUES (65,11,16,0,18,'ACTIVE');
INSERT INTO Ticket (ShowtimeID,SeatNumber,CustomerID,Discount,Price,Status) VALUES (24,7,18,0.1,18,'ACTIVE');
INSERT INTO Ticket (ShowtimeID,SeatNumber,CustomerID,Discount,Price,Status) VALUES (32,127,52,0,15,'ACTIVE');
INSERT INTO Ticket (ShowtimeID,SeatNumber,CustomerID,Discount,Price,Status) VALUES (17,109,17,0.2,18,'ACTIVE');
INSERT INTO Ticket (ShowtimeID,SeatNumber,CustomerID,Discount,Price,Status) VALUES (34,108,24,0,16,'ACTIVE');
INSERT INTO Ticket (ShowtimeID,SeatNumber,CustomerID,Discount,Price,Status) VALUES (58,132,43,0.1,12,'ACTIVE');
INSERT INTO Ticket (ShowtimeID,SeatNumber,CustomerID,Discount,Price,Status) VALUES (17,133,9,0.2,13,'ACTIVE');
INSERT INTO Ticket (ShowtimeID,SeatNumber,CustomerID,Discount,Price,Status) VALUES (66,140,15,0,15,'ACTIVE');
INSERT INTO Ticket (ShowtimeID,SeatNumber,CustomerID,Discount,Price,Status) VALUES (43,71,45,0.2,12,'ACTIVE');
INSERT INTO Ticket (ShowtimeID,SeatNumber,CustomerID,Discount,Price,Status) VALUES (41,47,18,0,14,'ACTIVE');
INSERT INTO Ticket (ShowtimeID,SeatNumber,CustomerID,Discount,Price,Status) VALUES (55,87,57,0.1,17,'ACTIVE');
INSERT INTO Ticket (ShowtimeID,SeatNumber,CustomerID,Discount,Price,Status) VALUES (39,49,30,0.2,17,'ACTIVE');
INSERT INTO Ticket (ShowtimeID,SeatNumber,CustomerID,Discount,Price,Status) VALUES (41,58,40,0,18,'ACTIVE');
INSERT INTO Ticket (ShowtimeID,SeatNumber,CustomerID,Discount,Price,Status) VALUES (70,106,27,0.2,17,'ACTIVE');
INSERT INTO Ticket (ShowtimeID,SeatNumber,CustomerID,Discount,Price,Status) VALUES (60,63,52,0.1,16,'ACTIVE');
INSERT INTO Ticket (ShowtimeID,SeatNumber,CustomerID,Discount,Price,Status) VALUES (71,3,1,0,18,'ACTIVE');
INSERT INTO Ticket (ShowtimeID,SeatNumber,CustomerID,Discount,Price,Status) VALUES (17,34,57,0.1,17,'ACTIVE');
INSERT INTO Ticket (ShowtimeID,SeatNumber,CustomerID,Discount,Price,Status) VALUES (26,69,38,0.1,14,'ACTIVE');
INSERT INTO Ticket (ShowtimeID,SeatNumber,CustomerID,Discount,Price,Status) VALUES (60,97,26,0.1,12,'ACTIVE');
INSERT INTO Ticket (ShowtimeID,SeatNumber,CustomerID,Discount,Price,Status) VALUES (68,125,29,0.1,16,'ACTIVE');
INSERT INTO Ticket (ShowtimeID,SeatNumber,CustomerID,Discount,Price,Status) VALUES (13,63,33,0,14,'ACTIVE');
INSERT INTO Ticket (ShowtimeID,SeatNumber,CustomerID,Discount,Price,Status) VALUES (10,85,26,0.1,18,'ACTIVE');
INSERT INTO Ticket (ShowtimeID,SeatNumber,CustomerID,Discount,Price,Status) VALUES (42,102,29,0.1,13,'ACTIVE');
INSERT INTO Ticket (ShowtimeID,SeatNumber,CustomerID,Discount,Price,Status) VALUES (60,24,30,0.2,14,'ACTIVE');
INSERT INTO Ticket (ShowtimeID,SeatNumber,CustomerID,Discount,Price,Status) VALUES (29,138,20,0.2,16,'ACTIVE');
INSERT INTO Ticket (ShowtimeID,SeatNumber,CustomerID,Discount,Price,Status) VALUES (25,14,43,0.2,17,'ACTIVE');
INSERT INTO Ticket (ShowtimeID,SeatNumber,CustomerID,Discount,Price,Status) VALUES (38,50,39,0.2,13,'ACTIVE');
INSERT INTO Ticket (ShowtimeID,SeatNumber,CustomerID,Discount,Price,Status) VALUES (30,54,50,0,18,'ACTIVE');
INSERT INTO Ticket (ShowtimeID,SeatNumber,CustomerID,Discount,Price,Status) VALUES (70,115,14,0,17,'ACTIVE');
INSERT INTO Ticket (ShowtimeID,SeatNumber,CustomerID,Discount,Price,Status) VALUES (29,42,24,0,18,'ACTIVE');
INSERT INTO Ticket (ShowtimeID,SeatNumber,CustomerID,Discount,Price,Status) VALUES (28,35,42,0.1,14,'ACTIVE');
INSERT INTO Ticket (ShowtimeID,SeatNumber,CustomerID,Discount,Price,Status) VALUES (73,3,1,0.1,12,'ACTIVE');
INSERT INTO Ticket (ShowtimeID,SeatNumber,CustomerID,Discount,Price,Status) VALUES (36,86,34,0,12,'ACTIVE');
INSERT INTO Ticket (ShowtimeID,SeatNumber,CustomerID,Discount,Price,Status) VALUES (73,28,44,0.2,13,'ACTIVE');
INSERT INTO Ticket (ShowtimeID,SeatNumber,CustomerID,Discount,Price,Status) VALUES (9,93,39,0.2,19,'ACTIVE');
INSERT INTO Ticket (ShowtimeID,SeatNumber,CustomerID,Discount,Price,Status) VALUES (58,2,24,0.1,14,'ACTIVE');
INSERT INTO Ticket (ShowtimeID,SeatNumber,CustomerID,Discount,Price,Status) VALUES (76,93,32,0,12,'ACTIVE');
INSERT INTO Ticket (ShowtimeID,SeatNumber,CustomerID,Discount,Price,Status) VALUES (58,43,40,0.2,15,'ACTIVE');
INSERT INTO Ticket (ShowtimeID,SeatNumber,CustomerID,Discount,Price,Status) VALUES (69,61,15,0.1,15,'ACTIVE');
INSERT INTO Ticket (ShowtimeID,SeatNumber,CustomerID,Discount,Price,Status) VALUES (52,110,22,0,17,'ACTIVE');
INSERT INTO Ticket (ShowtimeID,SeatNumber,CustomerID,Discount,Price,Status) VALUES (63,86,44,0.2,19,'ACTIVE');
INSERT INTO Ticket (ShowtimeID,SeatNumber,CustomerID,Discount,Price,Status) VALUES (16,81,33,0.1,17,'ACTIVE');
INSERT INTO Ticket (ShowtimeID,SeatNumber,CustomerID,Discount,Price,Status) VALUES (26,74,15,0.2,15,'ACTIVE');
INSERT INTO Ticket (ShowtimeID,SeatNumber,CustomerID,Discount,Price,Status) VALUES (8,68,39,0.1,19,'ACTIVE');
INSERT INTO Ticket (ShowtimeID,SeatNumber,CustomerID,Discount,Price,Status) VALUES (69,46,53,0,14,'ACTIVE');
INSERT INTO Ticket (ShowtimeID,SeatNumber,CustomerID,Discount,Price,Status) VALUES (7,69,11,0,14,'ACTIVE');
INSERT INTO Ticket (ShowtimeID,SeatNumber,CustomerID,Discount,Price,Status) VALUES (25,133,14,0.1,15,'ACTIVE');
INSERT INTO Ticket (ShowtimeID,SeatNumber,CustomerID,Discount,Price,Status) VALUES (44,31,10,0.1,14,'ACTIVE');
INSERT INTO Ticket (ShowtimeID,SeatNumber,CustomerID,Discount,Price,Status) VALUES (38,71,15,0.2,16,'ACTIVE');
INSERT INTO Ticket (ShowtimeID,SeatNumber,CustomerID,Discount,Price,Status) VALUES (42,125,54,0.2,12,'ACTIVE');
INSERT INTO Ticket (ShowtimeID,SeatNumber,CustomerID,Discount,Price,Status) VALUES (29,116,45,0.1,18,'ACTIVE');
INSERT INTO Ticket (ShowtimeID,SeatNumber,CustomerID,Discount,Price,Status) VALUES (44,79,32,0,15,'ACTIVE');
INSERT INTO Ticket (ShowtimeID,SeatNumber,CustomerID,Discount,Price,Status) VALUES (33,43,28,0.1,17,'ACTIVE');
INSERT INTO Ticket (ShowtimeID,SeatNumber,CustomerID,Discount,Price,Status) VALUES (66,77,59,0.2,15,'ACTIVE');
INSERT INTO Ticket (ShowtimeID,SeatNumber,CustomerID,Discount,Price,Status) VALUES (75,6,16,0.2,16,'ACTIVE');
INSERT INTO Ticket (ShowtimeID,SeatNumber,CustomerID,Discount,Price,Status) VALUES (62,9,30,0.1,12,'ACTIVE');
INSERT INTO Ticket (ShowtimeID,SeatNumber,CustomerID,Discount,Price,Status) VALUES (32,3,20,0.2,18,'ACTIVE');
INSERT INTO Ticket (ShowtimeID,SeatNumber,CustomerID,Discount,Price,Status) VALUES (32,59,55,0.2,17,'ACTIVE');
INSERT INTO Ticket (ShowtimeID,SeatNumber,CustomerID,Discount,Price,Status) VALUES (10,28,22,0.2,14,'ACTIVE');
INSERT INTO Ticket (ShowtimeID,SeatNumber,CustomerID,Discount,Price,Status) VALUES (71,92,7,0,18,'ACTIVE');
INSERT INTO Ticket (ShowtimeID,SeatNumber,CustomerID,Discount,Price,Status) VALUES (28,23,32,0.2,15,'ACTIVE');
INSERT INTO Ticket (ShowtimeID,SeatNumber,CustomerID,Discount,Price,Status) VALUES (35,55,24,0,13,'ACTIVE');
INSERT INTO Ticket (ShowtimeID,SeatNumber,CustomerID,Discount,Price,Status) VALUES (37,7,1,0,17,'ACTIVE');
INSERT INTO Ticket (ShowtimeID,SeatNumber,CustomerID,Discount,Price,Status) VALUES (34,126,57,0.1,17,'ACTIVE');
INSERT INTO Ticket (ShowtimeID,SeatNumber,CustomerID,Discount,Price,Status) VALUES (53,84,33,0,14,'ACTIVE');
INSERT INTO Ticket (ShowtimeID,SeatNumber,CustomerID,Discount,Price,Status) VALUES (18,7,53,0.2,15,'ACTIVE');
INSERT INTO Ticket (ShowtimeID,SeatNumber,CustomerID,Discount,Price,Status) VALUES (66,124,54,0.1,19,'ACTIVE');
INSERT INTO Ticket (ShowtimeID,SeatNumber,CustomerID,Discount,Price,Status) VALUES (73,106,7,0.1,12,'ACTIVE');
INSERT INTO Ticket (ShowtimeID,SeatNumber,CustomerID,Discount,Price,Status) VALUES (79,120,5,0.1,18,'ACTIVE');
INSERT INTO Ticket (ShowtimeID,SeatNumber,CustomerID,Discount,Price,Status) VALUES (14,3,53,0.2,13,'ACTIVE');
INSERT INTO Ticket (ShowtimeID,SeatNumber,CustomerID,Discount,Price,Status) VALUES (53,53,59,0.1,18,'ACTIVE');
INSERT INTO Ticket (ShowtimeID,SeatNumber,CustomerID,Discount,Price,Status) VALUES (5,11,2,0.1,19,'ACTIVE');
INSERT INTO Ticket (ShowtimeID,SeatNumber,CustomerID,Discount,Price,Status) VALUES (11,139,18,0.1,19,'ACTIVE');
INSERT INTO Ticket (ShowtimeID,SeatNumber,CustomerID,Discount,Price,Status) VALUES (54,54,57,0,14,'ACTIVE');
INSERT INTO Ticket (ShowtimeID,SeatNumber,CustomerID,Discount,Price,Status) VALUES (13,69,37,0,18,'ACTIVE');
INSERT INTO Ticket (ShowtimeID,SeatNumber,CustomerID,Discount,Price,Status) VALUES (71,45,22,0.2,18,'ACTIVE');
INSERT INTO Ticket (ShowtimeID,SeatNumber,CustomerID,Discount,Price,Status) VALUES (11,91,40,0,15,'ACTIVE');
INSERT INTO Ticket (ShowtimeID,SeatNumber,CustomerID,Discount,Price,Status) VALUES (63,67,23,0,17,'ACTIVE');
INSERT INTO Ticket (ShowtimeID,SeatNumber,CustomerID,Discount,Price,Status) VALUES (59,48,48,0.1,13,'ACTIVE');
INSERT INTO Ticket (ShowtimeID,SeatNumber,CustomerID,Discount,Price,Status) VALUES (67,95,14,0,18,'ACTIVE');
INSERT INTO Ticket (ShowtimeID,SeatNumber,CustomerID,Discount,Price,Status) VALUES (58,28,22,0,15,'ACTIVE');
INSERT INTO Ticket (ShowtimeID,SeatNumber,CustomerID,Discount,Price,Status) VALUES (16,8,3,0.1,19,'ACTIVE');
INSERT INTO Ticket (ShowtimeID,SeatNumber,CustomerID,Discount,Price,Status) VALUES (13,3,56,0.1,17,'ACTIVE');
INSERT INTO Ticket (ShowtimeID,SeatNumber,CustomerID,Discount,Price,Status) VALUES (56,69,4,0,15,'ACTIVE');
INSERT INTO Ticket (ShowtimeID,SeatNumber,CustomerID,Discount,Price,Status) VALUES (53,66,43,0.2,15,'ACTIVE');
INSERT INTO Ticket (ShowtimeID,SeatNumber,CustomerID,Discount,Price,Status) VALUES (14,22,3,0.2,17,'ACTIVE');
INSERT INTO Ticket (ShowtimeID,SeatNumber,CustomerID,Discount,Price,Status) VALUES (50,114,13,0.1,14,'ACTIVE');
INSERT INTO Ticket (ShowtimeID,SeatNumber,CustomerID,Discount,Price,Status) VALUES (34,108,28,0.1,12,'ACTIVE');
INSERT INTO Ticket (ShowtimeID,SeatNumber,CustomerID,Discount,Price,Status) VALUES (52,2,60,0.2,14,'ACTIVE');
INSERT INTO Ticket (ShowtimeID,SeatNumber,CustomerID,Discount,Price,Status) VALUES (69,26,36,0,15,'ACTIVE');
INSERT INTO Ticket (ShowtimeID,SeatNumber,CustomerID,Discount,Price,Status) VALUES (36,97,30,0,13,'ACTIVE');
INSERT INTO Ticket (ShowtimeID,SeatNumber,CustomerID,Discount,Price,Status) VALUES (8,106,7,0.2,16,'ACTIVE');
INSERT INTO Ticket (ShowtimeID,SeatNumber,CustomerID,Discount,Price,Status) VALUES (19,63,50,0,17,'ACTIVE');
INSERT INTO Ticket (ShowtimeID,SeatNumber,CustomerID,Discount,Price,Status) VALUES (28,108,28,0.1,16,'ACTIVE');
INSERT INTO Ticket (ShowtimeID,SeatNumber,CustomerID,Discount,Price,Status) VALUES (42,7,22,0,12,'ACTIVE');
INSERT INTO Ticket (ShowtimeID,SeatNumber,CustomerID,Discount,Price,Status) VALUES (70,50,5,0,16,'ACTIVE');
INSERT INTO Ticket (ShowtimeID,SeatNumber,CustomerID,Discount,Price,Status) VALUES (13,8,12,0,15,'ACTIVE');
INSERT INTO Ticket (ShowtimeID,SeatNumber,CustomerID,Discount,Price,Status) VALUES (31,63,54,0,19,'ACTIVE');
INSERT INTO Ticket (ShowtimeID,SeatNumber,CustomerID,Discount,Price,Status) VALUES (74,94,25,0.1,16,'ACTIVE');
INSERT INTO Ticket (ShowtimeID,SeatNumber,CustomerID,Discount,Price,Status) VALUES (19,73,5,0,16,'ACTIVE');
INSERT INTO Ticket (ShowtimeID,SeatNumber,CustomerID,Discount,Price,Status) VALUES (80,79,17,0.2,13,'ACTIVE');
INSERT INTO Ticket (ShowtimeID,SeatNumber,CustomerID,Discount,Price,Status) VALUES (71,142,9,0.1,12,'ACTIVE');
INSERT INTO Ticket (ShowtimeID,SeatNumber,CustomerID,Discount,Price,Status) VALUES (13,108,56,0,17,'ACTIVE');
INSERT INTO Ticket (ShowtimeID,SeatNumber,CustomerID,Discount,Price,Status) VALUES (69,105,37,0.2,15,'ACTIVE');
INSERT INTO Ticket (ShowtimeID,SeatNumber,CustomerID,Discount,Price,Status) VALUES (54,89,14,0.1,19,'ACTIVE');
INSERT INTO Ticket (ShowtimeID,SeatNumber,CustomerID,Discount,Price,Status) VALUES (44,117,22,0.2,12,'ACTIVE');
INSERT INTO Ticket (ShowtimeID,SeatNumber,CustomerID,Discount,Price,Status) VALUES (2,130,10,0.2,17,'ACTIVE');
INSERT INTO Ticket (ShowtimeID,SeatNumber,CustomerID,Discount,Price,Status) VALUES (8,96,14,0,15,'ACTIVE');
INSERT INTO Ticket (ShowtimeID,SeatNumber,CustomerID,Discount,Price,Status) VALUES (38,88,48,0.1,19,'ACTIVE');
INSERT INTO Ticket (ShowtimeID,SeatNumber,CustomerID,Discount,Price,Status) VALUES (43,6,44,0.2,16,'ACTIVE');
INSERT INTO Ticket (ShowtimeID,SeatNumber,CustomerID,Discount,Price,Status) VALUES (25,122,20,0.1,16,'ACTIVE');
INSERT INTO Ticket (ShowtimeID,SeatNumber,CustomerID,Discount,Price,Status) VALUES (44,47,8,0.1,18,'ACTIVE');
INSERT INTO Ticket (ShowtimeID,SeatNumber,CustomerID,Discount,Price,Status) VALUES (70,100,27,0.2,17,'ACTIVE');
INSERT INTO Ticket (ShowtimeID,SeatNumber,CustomerID,Discount,Price,Status) VALUES (35,95,33,0,19,'ACTIVE');
INSERT INTO Ticket (ShowtimeID,SeatNumber,CustomerID,Discount,Price,Status) VALUES (21,41,19,0.2,18,'ACTIVE');
INSERT INTO Ticket (ShowtimeID,SeatNumber,CustomerID,Discount,Price,Status) VALUES (31,93,7,0,12,'ACTIVE');
INSERT INTO Ticket (ShowtimeID,SeatNumber,CustomerID,Discount,Price,Status) VALUES (46,59,9,0.1,14,'ACTIVE');
INSERT INTO Ticket (ShowtimeID,SeatNumber,CustomerID,Discount,Price,Status) VALUES (42,83,4,0,13,'ACTIVE');
INSERT INTO Ticket (ShowtimeID,SeatNumber,CustomerID,Discount,Price,Status) VALUES (27,69,57,0.1,19,'ACTIVE');
INSERT INTO Ticket (ShowtimeID,SeatNumber,CustomerID,Discount,Price,Status) VALUES (42,77,26,0.1,18,'ACTIVE');
INSERT INTO Ticket (ShowtimeID,SeatNumber,CustomerID,Discount,Price,Status) VALUES (68,50,4,0,18,'ACTIVE');
INSERT INTO Ticket (ShowtimeID,SeatNumber,CustomerID,Discount,Price,Status) VALUES (21,83,26,0.1,13,'ACTIVE');
INSERT INTO Ticket (ShowtimeID,SeatNumber,CustomerID,Discount,Price,Status) VALUES (33,33,8,0.2,13,'ACTIVE');